/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visaoUsuario;

import visaoMaster.*;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import Beans.BeansDestinos;
import Beans.BeansMarca;
import Beans.BeansTabelas;
import modeloConection.ConexaoBD;
import modeloDao.DaoDestinos;
import controller.UpperCase;
import visaoMaster.TbATabelasAuxiliares;
import visaoMaster.JanelaPadrao;

/**
 *
 * @author Professor
 */
public class Destinos extends javax.swing.JFrame {

    BeansDestinos modDest = new BeansDestinos();
    DaoDestinos control = new DaoDestinos();
    ConexaoBD conex = new ConexaoBD();
    
    public Destinos() {
        initComponents();
        jInternalFrameBuscaDestino.setVisible(false);
        jButtonEditar.setEnabled(false);
        jButtonApagar.setEnabled(false);
        jButtonImprimir.setEnabled(false);
        jTextFieldDescricao.setDocument(new UpperCase());
        jLabelDescObgt.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrameBuscaDestino = new javax.swing.JInternalFrame();
        jScrollPaneDestino = new javax.swing.JScrollPane();
        jTableDestinos = new javax.swing.JTable();
        jButtonSairIF = new javax.swing.JButton();
        jButtonPesquisarIF = new javax.swing.JButton();
        jLabelFaixaMenu1 = new javax.swing.JLabel();
        JlabelFundoMenuIF = new javax.swing.JLabel();
        jLabelCod = new javax.swing.JLabel();
        jLabelDescricao = new javax.swing.JLabel();
        jTextFieldDescricao = new javax.swing.JTextField();
        jLabelDescObgt = new javax.swing.JLabel();
        jTextFieldCod = new javax.swing.JTextField();
        jButtonIncluir = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonApagar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jButtonPesquisar = new javax.swing.JButton();
        jButtonImprimir = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelFaixaMenu = new javax.swing.JLabel();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastrar destinos");
        setResizable(false);
        getContentPane().setLayout(null);

        jInternalFrameBuscaDestino.setTitle("Selecionar Destino");
        jInternalFrameBuscaDestino.setVisible(true);
        jInternalFrameBuscaDestino.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableDestinos.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jTableDestinos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableDestinos.setGridColor(new java.awt.Color(255, 255, 255));
        jTableDestinos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDestinosMouseClicked(evt);
            }
        });
        jScrollPaneDestino.setViewportView(jTableDestinos);

        jInternalFrameBuscaDestino.getContentPane().add(jScrollPaneDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 410, 130));

        jButtonSairIF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/sair.png"))); // NOI18N
        jButtonSairIF.setToolTipText("Sair");
        jButtonSairIF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairIFActionPerformed(evt);
            }
        });
        jInternalFrameBuscaDestino.getContentPane().add(jButtonSairIF, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 45, 30));

        jButtonPesquisarIF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/pesquisar.png"))); // NOI18N
        jButtonPesquisarIF.setToolTipText("Buscar");
        jButtonPesquisarIF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarIFActionPerformed(evt);
            }
        });
        jInternalFrameBuscaDestino.getContentPane().add(jButtonPesquisarIF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 45, 30));

        jLabelFaixaMenu1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFaixaMenu1.setForeground(new java.awt.Color(102, 255, 255));
        jLabelFaixaMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menuprincipal_Faixa.png"))); // NOI18N
        jInternalFrameBuscaDestino.getContentPane().add(jLabelFaixaMenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 30));

        JlabelFundoMenuIF.setBackground(new java.awt.Color(255, 255, 255));
        JlabelFundoMenuIF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menuprincipal_fundo.png"))); // NOI18N
        JlabelFundoMenuIF.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jInternalFrameBuscaDestino.getContentPane().add(JlabelFundoMenuIF, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 10, 420, 180));

        getContentPane().add(jInternalFrameBuscaDestino);
        jInternalFrameBuscaDestino.setBounds(30, 10, 430, 190);

        jLabelCod.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelCod.setText("Código:");
        getContentPane().add(jLabelCod);
        jLabelCod.setBounds(30, 50, 60, 25);

        jLabelDescricao.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelDescricao.setText("Descrição:");
        getContentPane().add(jLabelDescricao);
        jLabelDescricao.setBounds(30, 90, 60, 25);

        jTextFieldDescricao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDescricaoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldDescricao);
        jTextFieldDescricao.setBounds(100, 90, 260, 25);

        jLabelDescObgt.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabelDescObgt.setForeground(new java.awt.Color(255, 0, 0));
        jLabelDescObgt.setText("Obrigatório");
        getContentPane().add(jLabelDescObgt);
        jLabelDescObgt.setBounds(360, 90, 70, 20);

        jTextFieldCod.setEditable(false);
        jTextFieldCod.setEnabled(false);
        jTextFieldCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCod);
        jTextFieldCod.setBounds(100, 50, 60, 25);

        jButtonIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/incluir.png"))); // NOI18N
        jButtonIncluir.setToolTipText("Incluir");
        jButtonIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonIncluir);
        jButtonIncluir.setBounds(10, 0, 45, 30);

        jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/salvar.png"))); // NOI18N
        jButtonEditar.setToolTipText("Salvar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEditar);
        jButtonEditar.setBounds(60, 0, 45, 30);

        jButtonApagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/apagar.png"))); // NOI18N
        jButtonApagar.setToolTipText("Deletar");
        jButtonApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApagarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonApagar);
        jButtonApagar.setBounds(110, 0, 45, 30);

        jButtonLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/limpar.png"))); // NOI18N
        jButtonLimpar.setToolTipText("Limpar");
        jButtonLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonLimparMouseClicked(evt);
            }
        });
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLimpar);
        jButtonLimpar.setBounds(160, 0, 45, 30);

        jButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/pesquisar.png"))); // NOI18N
        jButtonPesquisar.setToolTipText("Buscar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPesquisar);
        jButtonPesquisar.setBounds(210, 0, 45, 30);

        jButtonImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/imprimir.png"))); // NOI18N
        jButtonImprimir.setToolTipText("Imprimir");
        getContentPane().add(jButtonImprimir);
        jButtonImprimir.setBounds(260, 0, 45, 30);

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/sair.png"))); // NOI18N
        jButtonSair.setToolTipText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSair);
        jButtonSair.setBounds(310, 0, 45, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("* Campos de preenchimento obrigatório.");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 160, 220, 14);

        jLabelFaixaMenu.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFaixaMenu.setForeground(new java.awt.Color(102, 255, 255));
        jLabelFaixaMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menuprincipal_Faixa.png"))); // NOI18N
        getContentPane().add(jLabelFaixaMenu);
        jLabelFaixaMenu.setBounds(0, 0, 500, 30);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menuprincipal_fundo.png"))); // NOI18N
        getContentPane().add(jLabelFundo);
        jLabelFundo.setBounds(0, 30, 500, 180);

        setSize(new java.awt.Dimension(505, 239));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        TbATabelasAuxiliares tbausuario = new TbATabelasAuxiliares();
        tbausuario.setVisible(true);
        dispose();        
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLimparMouseClicked
        jTextFieldDescricao.setText("");
        jTextFieldCod.setText("");
        jButtonIncluir.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonApagar.setEnabled(false);
        jLabelDescObgt.setVisible(false);
    }//GEN-LAST:event_jButtonLimparMouseClicked

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jTableDestinosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDestinosMouseClicked
        String descricao = ""+jTableDestinos.getValueAt(jTableDestinos.getSelectedRow(), 1);

        conex.executaSql("select id_destino, descricao from tbl_destinos where descricao ilike '%"+descricao+"%'");
        try {
            conex.rs.first();
            modDest.setCodigo(conex.rs.getInt("id_destino"));
            modDest.setDescricao(conex.rs.getString("descricao"));

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Destino não encontrado"+ex);
        }

        jTextFieldCod.setText(String.valueOf(modDest.getCodigo()));
        jTextFieldDescricao.setText(modDest.getDescricao());

        conex.desconecta();
        jInternalFrameBuscaDestino.dispose();
        jButtonApagar.setEnabled(true);
        jButtonEditar.setEnabled(true);
        jButtonIncluir.setEnabled(false);
    }//GEN-LAST:event_jTableDestinosMouseClicked

    private void jButtonSairIFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairIFActionPerformed
        jInternalFrameBuscaDestino.dispose();
    }//GEN-LAST:event_jButtonSairIFActionPerformed

    private void jButtonPesquisarIFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarIFActionPerformed
        PreencherTabelaIF("select id_destino, descricao from tbl_destinos");

    }//GEN-LAST:event_jButtonPesquisarIFActionPerformed

    private void jTextFieldDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDescricaoActionPerformed

    }//GEN-LAST:event_jTextFieldDescricaoActionPerformed

    private void jTextFieldCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodActionPerformed

    }//GEN-LAST:event_jTextFieldCodActionPerformed

    private void jButtonIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirActionPerformed
       if(jTextFieldDescricao.getText().isEmpty()) {
          jLabelDescObgt.setVisible(true);
          JOptionPane.showMessageDialog(null, "Campo Obrigatório");
          jTextFieldDescricao.requestFocus();
        }else {
          modDest.setDescricao(jTextFieldDescricao.getText());
          control.Salvar(modDest);
          
            modDest.setDescricao(jTextFieldDescricao.getText());
            BeansDestinos model = control.Pesquisar(modDest);
            jTextFieldCod.setText(String.valueOf(model.getCodigo()));
          
          jLabelDescObgt.setVisible(false);
          jButtonIncluir.setEnabled(false);
          jButtonEditar.setEnabled(true);
          jButtonApagar.setEnabled(true);   
        }
    }//GEN-LAST:event_jButtonIncluirActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        if (jTextFieldDescricao.getText().length() > 0) { 
                modDest.setCodigo(Integer.parseInt(jTextFieldCod.getText()));
                modDest.setDescricao(jTextFieldDescricao.getText());
                control.Editar(modDest);
                jLabelDescObgt.setVisible(false);
            }
            else {
                jLabelDescObgt.setVisible(true);
                JOptionPane.showMessageDialog(null, "Campo Obrigatório");
                jTextFieldDescricao.requestFocus();    
            }   
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        PreencherTabelaIF("select id_destino, descricao from tbl_destinos");
        jInternalFrameBuscaDestino.setVisible(true);
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApagarActionPerformed
        int Confirm = JOptionPane.showConfirmDialog(null,"Excluir registro?"," Excluir", JOptionPane.YES_NO_OPTION);
            if (Confirm == JOptionPane.YES_OPTION) {
            modDest.setCodigo(Integer.parseInt(jTextFieldCod.getText()));
            modDest.setDescricao(jTextFieldDescricao.getText());
            control.Excluir(modDest);
            
            jTextFieldDescricao.setText("");
            jTextFieldCod.setText("");
            jButtonEditar.setEnabled(false);
            jButtonApagar.setEnabled(false);
            jLabelDescObgt.setVisible(false);
            jButtonIncluir.setEnabled(true);
            }else if (Confirm == JOptionPane.NO_OPTION){
                setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            }
    }//GEN-LAST:event_jButtonApagarActionPerformed

    
    public void PreencherTabelaIF(String SQL){
      ArrayList dados = new ArrayList();
      String[] colunas = new String[]{"COD","DESTINO"};
      
      conex.conexao();
      conex.executaSql(SQL);

      try{
          conex.rs.first();       
          do{
              dados.add(new Object[]{conex.rs.getInt("id_destino"),
                                     conex.rs.getString("descricao")
                                   
                                    });
 
          }while(conex.rs.next());
      
        }catch(SQLException ex){
          JOptionPane.showMessageDialog(null, "Erro ao preencher ArrayList\nErro:"+ex);
        }
          
     BeansTabelas modelo = new BeansTabelas(dados, colunas);
      
     jTableDestinos.setModel(modelo);
     jTableDestinos.getColumnModel().getColumn(0).setPreferredWidth(45);
     jTableDestinos.getColumnModel().getColumn(0).setResizable(true);
     jTableDestinos.getColumnModel().getColumn(0).setHeaderValue("COD");
     jTableDestinos.getColumnModel().getColumn(1).setPreferredWidth(342);
     jTableDestinos.getColumnModel().getColumn(1).setResizable(true); //não redimensionaveL
     jTableDestinos.getColumnModel().getColumn(1).setHeaderValue("DESTINO");
           

     jTableDestinos.getTableHeader().setReorderingAllowed(false); //não reordenavel
     jTableDestinos.setAutoResizeMode(jTableDestinos.AUTO_RESIZE_OFF); //não redmencionar
     jTableDestinos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);//selicioar um dado por vez
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPadrao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPadrao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPadrao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPadrao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPadrao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JlabelFundoMenuIF;
    private javax.swing.JButton jButtonApagar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonImprimir;
    private javax.swing.JButton jButtonIncluir;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonPesquisarIF;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSairIF;
    private javax.swing.JInternalFrame jInternalFrameBuscaDestino;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCod;
    private javax.swing.JLabel jLabelDescObgt;
    private javax.swing.JLabel jLabelDescricao;
    private javax.swing.JLabel jLabelFaixaMenu;
    private javax.swing.JLabel jLabelFaixaMenu1;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JScrollPane jScrollPaneDestino;
    private javax.swing.JTable jTableDestinos;
    private javax.swing.JTextField jTextFieldCod;
    private javax.swing.JTextField jTextFieldDescricao;
    // End of variables declaration//GEN-END:variables
}
