/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visaoUsuario;

import modeloConection.ConexaoBD;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import Beans.BeansLogin;
import modeloDao.DaoLogin;
import visaoMaster.AlterarSenha;
import visaoMaster.CadACadastros;
import visaoMaster.CadMotorista;
import visaoMaster.CadUsuarios;
import visaoMaster.CadVeiculos;
import visaoMaster.Login;
import visaoMaster.RegistrarAtiv;
import visaoMaster.RelARelatorios;
import visaoMaster.RelRegPorAtividade;
import visaoMaster.RelRegPorMotorista;
import visaoMaster.RelRegPorSetor;
import visaoMaster.RelRegPorVeiculo;
import visaoMaster.TbDestinos;
import visaoMaster.TbMarca;
import visaoMaster.TbModelo;
import visaoMaster.TbTipoAtividade;

/**
 *
 * @author Professor
 */
public class MenuPrincipal extends javax.swing.JFrame {

    ConexaoBD conecta = new ConexaoBD();
    BeansLogin mod = new BeansLogin();
    DaoLogin control = new DaoLogin();
    
    
    public MenuPrincipal(String usuario) {
        initComponents();
        conecta.conexao();
        jButtonRel.setEnabled(false);
        
        
        jTextFieldUser.setText(usuario);
        
            mod.setUsuario(jTextFieldUser.getText());
            BeansLogin model = control.PesquisarUsuario(mod);
            jTextFieldNomeUser.setText("-"+model.getNome());
            
        
       // BeansLogin model = control.Pesquisar(mod);
       // jTextFieldUser.setText(model.getUsuario());
        
        
    }

    private MenuPrincipal() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNameInst = new javax.swing.JLabel();
        jLabelNameSetor = new javax.swing.JLabel();
        jLabelAlterSenha = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jTextFieldUser = new javax.swing.JTextField();
        jTextFieldNomeUser = new javax.swing.JTextField();
        jButtonSairAmeba = new javax.swing.JButton();
        jButtonCadastros = new javax.swing.JButton();
        jButtonRegistrar = new javax.swing.JButton();
        jButtonRel = new javax.swing.JButton();
        jButtonTabAux = new javax.swing.JButton();
        jComboBoxAcesoRapido = new javax.swing.JComboBox<>();
        jLabelLogoIMCG = new javax.swing.JLabel();
        jButtonSair = new javax.swing.JButton();
        jLabelDesenvolvimentoMenu = new javax.swing.JLabel();
        jLabelFaixaInfeior = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        MirinsGrama = new javax.swing.JLabel();
        jLabelFaixaSuperior = new javax.swing.JLabel();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Ctrl-T - Controle de Tráfego");
        setResizable(false);
        getContentPane().setLayout(null);

        jLabelNameInst.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelNameInst.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNameInst.setText("INSTITUTO MIRIM DE CAMPO GRANDE");
        getContentPane().add(jLabelNameInst);
        jLabelNameInst.setBounds(490, 20, 380, 30);

        jLabelNameSetor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelNameSetor.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNameSetor.setText("Núcleo de Tecnologia da Informação");
        getContentPane().add(jLabelNameSetor);
        jLabelNameSetor.setBounds(1060, 650, 260, 40);

        jLabelAlterSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/altSenha.png"))); // NOI18N
        jLabelAlterSenha.setToolTipText("Clique aqui para alterar sua senha");
        jLabelAlterSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAlterSenhaMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelAlterSenha);
        jLabelAlterSenha.setBounds(1330, 660, 23, 23);

        jLabelUsuario.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(255, 102, 51));
        jLabelUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelUsuario.setText("USUÁRIO:");
        getContentPane().add(jLabelUsuario);
        jLabelUsuario.setBounds(580, 650, 70, 20);

        jTextFieldUser.setEditable(false);
        jTextFieldUser.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldUser.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextFieldUser.setForeground(new java.awt.Color(255, 102, 51));
        jTextFieldUser.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldUser.setBorder(null);
        getContentPane().add(jTextFieldUser);
        jTextFieldUser.setBounds(650, 650, 60, 20);

        jTextFieldNomeUser.setEditable(false);
        jTextFieldNomeUser.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldNomeUser.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextFieldNomeUser.setForeground(new java.awt.Color(255, 102, 51));
        jTextFieldNomeUser.setBorder(null);
        getContentPane().add(jTextFieldNomeUser);
        jTextFieldNomeUser.setBounds(710, 650, 140, 20);

        jButtonSairAmeba.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSairAmeba.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonSairAmeba.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSairAmeba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/IconAmeba.png"))); // NOI18N
        jButtonSairAmeba.setText("Sair");
        jButtonSairAmeba.setToolTipText("Sair do Sistema");
        jButtonSairAmeba.setBorder(null);
        jButtonSairAmeba.setBorderPainted(false);
        jButtonSairAmeba.setContentAreaFilled(false);
        jButtonSairAmeba.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSairAmeba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairAmebaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSairAmeba);
        jButtonSairAmeba.setBounds(980, 150, 180, 140);

        jButtonCadastros.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCadastros.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonCadastros.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCadastros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/IconAmeba.png"))); // NOI18N
        jButtonCadastros.setText("Cadastros");
        jButtonCadastros.setToolTipText("Cadastros");
        jButtonCadastros.setBorder(null);
        jButtonCadastros.setBorderPainted(false);
        jButtonCadastros.setContentAreaFilled(false);
        jButtonCadastros.setEnabled(false);
        jButtonCadastros.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCadastros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCadastrosMouseClicked(evt);
            }
        });
        jButtonCadastros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadastros);
        jButtonCadastros.setBounds(350, 150, 180, 140);

        jButtonRegistrar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRegistrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/IconAmeba.png"))); // NOI18N
        jButtonRegistrar.setText("Registrar ");
        jButtonRegistrar.setToolTipText("Registrar Atividade");
        jButtonRegistrar.setBorder(null);
        jButtonRegistrar.setBorderPainted(false);
        jButtonRegistrar.setContentAreaFilled(false);
        jButtonRegistrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRegistrarMouseClicked(evt);
            }
        });
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegistrar);
        jButtonRegistrar.setBounds(150, 150, 180, 140);

        jButtonRel.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonRel.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/IconAmeba.png"))); // NOI18N
        jButtonRel.setText("Relatórios");
        jButtonRel.setToolTipText("Relatórios");
        jButtonRel.setBorder(null);
        jButtonRel.setBorderPainted(false);
        jButtonRel.setContentAreaFilled(false);
        jButtonRel.setEnabled(false);
        jButtonRel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonRel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRel);
        jButtonRel.setBounds(560, 150, 180, 140);

        jButtonTabAux.setBackground(new java.awt.Color(255, 255, 255));
        jButtonTabAux.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonTabAux.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTabAux.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/IconAmeba.png"))); // NOI18N
        jButtonTabAux.setText("Tabelas Aux");
        jButtonTabAux.setToolTipText("Tabelas Auxiliares");
        jButtonTabAux.setBorder(null);
        jButtonTabAux.setBorderPainted(false);
        jButtonTabAux.setContentAreaFilled(false);
        jButtonTabAux.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonTabAux.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTabAuxActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonTabAux);
        jButtonTabAux.setBounds(770, 150, 180, 140);

        jComboBoxAcesoRapido.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxAcesoRapido.setMaximumRowCount(24);
        jComboBoxAcesoRapido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alterar Senha", "Destinos", "Registro de Atividadedes" }));
        jComboBoxAcesoRapido.setName(""); // NOI18N
        jComboBoxAcesoRapido.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxAcesoRapidoItemStateChanged(evt);
            }
        });
        jComboBoxAcesoRapido.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                jComboBoxAcesoRapidoCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jComboBoxAcesoRapido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAcesoRapidoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxAcesoRapido);
        jComboBoxAcesoRapido.setBounds(1170, 0, 160, 25);

        jLabelLogoIMCG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menuprincipal_LogoIMCG.png"))); // NOI18N
        getContentPane().add(jLabelLogoIMCG);
        jLabelLogoIMCG.setBounds(0, 0, 130, 60);

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sair.gif"))); // NOI18N
        jButtonSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSairMouseClicked(evt);
            }
        });
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSair);
        jButtonSair.setBounds(1340, 0, 20, 20);

        jLabelDesenvolvimentoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/loguin_Desenvolvimento.png"))); // NOI18N
        jLabelDesenvolvimentoMenu.setLabelFor(jLabelDesenvolvimentoMenu);
        getContentPane().add(jLabelDesenvolvimentoMenu);
        jLabelDesenvolvimentoMenu.setBounds(0, 640, 270, 70);

        jLabelFaixaInfeior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menuprincipal_FaixaInferior.png"))); // NOI18N
        getContentPane().add(jLabelFaixaInfeior);
        jLabelFaixaInfeior.setBounds(0, 650, 1690, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/aluno.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, -40, 1060, 1510);

        MirinsGrama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mirins.png"))); // NOI18N
        getContentPane().add(MirinsGrama);
        MirinsGrama.setBounds(1000, 310, 368, 340);

        jLabelFaixaSuperior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menuprincipal_Faixa.png"))); // NOI18N
        getContentPane().add(jLabelFaixaSuperior);
        jLabelFaixaSuperior.setBounds(-40, 0, 1420, 60);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menuprincipal_fundo.png"))); // NOI18N
        getContentPane().add(jLabelFundo);
        jLabelFundo.setBounds(0, 20, 1420, 740);

        setSize(new java.awt.Dimension(1372, 729));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSairMouseClicked
                                           
    // TODO add your handling code here:

    int Confirm = JOptionPane.showConfirmDialog(null,"Sair do sistema?"," Ctrl-T", JOptionPane.YES_NO_OPTION);
    if (Confirm == JOptionPane.YES_OPTION) {
        //JOptionPane.showMessageDialog(null, "Até breve ");
        conecta.desconecta();
        Login login = new Login();
        login.setVisible(true);
        dispose();
        //System.exit(0);
    } else if (Confirm == JOptionPane.NO_OPTION){
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }


    }//GEN-LAST:event_jButtonSairMouseClicked

    private void jComboBoxAcesoRapidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAcesoRapidoActionPerformed
        
       
        if(jComboBoxAcesoRapido.getSelectedItem().equals("Marca")){
        TbMarca marca = new TbMarca();
        marca.setVisible(true);
        }
       if(jComboBoxAcesoRapido.getSelectedItem().equals("Modelo")){
        TbModelo modelo = new TbModelo();
        modelo.setVisible(true);
        }
       if(jComboBoxAcesoRapido.getSelectedItem().equals("Motorista")){
        CadMotorista cadm = new CadMotorista();
        cadm.setVisible(true);
        }
       if(jComboBoxAcesoRapido.getSelectedItem().equals("Registro de Atividadedes")){
        visaoUsuario.RegistrarAtiv reg = new visaoUsuario.RegistrarAtiv();
        reg.setVisible(true);
        }
       if(jComboBoxAcesoRapido.getSelectedItem().equals("Tipo de Atividade")){
        TbTipoAtividade tb = new TbTipoAtividade();
        tb.setVisible(true);
        }
       if(jComboBoxAcesoRapido.getSelectedItem().equals("Veículo")){
        CadVeiculos cadv = new CadVeiculos();
        cadv.setVisible(true);
        }
       if(jComboBoxAcesoRapido.getSelectedItem().equals("Destinos")){
        TbDestinos tbd = new TbDestinos();
        tbd.setVisible(true);
        }
       if(jComboBoxAcesoRapido.getSelectedItem().equals("Usuários")){
        CadUsuarios cdu = new CadUsuarios();
        cdu.setVisible(true);
        }
       if(jComboBoxAcesoRapido.getSelectedItem().equals("Alterar Senha")){
        AlterarSenha alts = new AlterarSenha(jTextFieldUser.getText());
        alts.setVisible(true);
        }
       if(jComboBoxAcesoRapido.getSelectedItem().equals("Rel. Registro por Atividade")){
        RelRegPorAtividade rela = new RelRegPorAtividade();
        rela.setVisible(true);
        }
       if(jComboBoxAcesoRapido.getSelectedItem().equals("Rel. Registro por Motorista")){
        RelRegPorMotorista relm = new RelRegPorMotorista();
        relm.setVisible(true);
        }
       if(jComboBoxAcesoRapido.getSelectedItem().equals("Rel. Registro por Placa")){
        RelRegPorVeiculo relp = new RelRegPorVeiculo();
        relp.setVisible(true);
        }
       if(jComboBoxAcesoRapido.getSelectedItem().equals("Rel. Registro por Setor")){
        RelRegPorSetor rels = new RelRegPorSetor();
        rels.setVisible(true);
        }

    /*


*/

        

    }//GEN-LAST:event_jComboBoxAcesoRapidoActionPerformed

    private void jButtonSairAmebaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairAmebaActionPerformed
        
        int Confirm = JOptionPane.showConfirmDialog(null,"Sair do sistema?"," Ctrl-T", JOptionPane.YES_NO_OPTION);
            if (Confirm == JOptionPane.YES_OPTION) {
            //JOptionPane.showMessageDialog(null, " Até breve ");
            conecta.desconecta();
            Login login = new Login();
            login.setVisible(true);
            dispose();
            
            //System.exit(0);
            } else if (Confirm == JOptionPane.NO_OPTION){
                setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
                
    }//GEN-LAST:event_jButtonSairAmebaActionPerformed
   } 
    private void jButtonRelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelActionPerformed
        RelARelatorios rel = new RelARelatorios();
        rel.setVisible(true);
    }//GEN-LAST:event_jButtonRelActionPerformed

    private void jButtonTabAuxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTabAuxActionPerformed
      visaoUsuario.TbATabelasAuxiliares selecTab = new visaoUsuario.TbATabelasAuxiliares();
      selecTab.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButtonTabAuxActionPerformed

    private void jButtonCadastrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCadastrosMouseClicked
                
    }//GEN-LAST:event_jButtonCadastrosMouseClicked

    private void jButtonRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRegistrarMouseClicked
                
    }//GEN-LAST:event_jButtonRegistrarMouseClicked

    private void jComboBoxAcesoRapidoCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jComboBoxAcesoRapidoCaretPositionChanged
        
    }//GEN-LAST:event_jComboBoxAcesoRapidoCaretPositionChanged

    private void jComboBoxAcesoRapidoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxAcesoRapidoItemStateChanged

    }//GEN-LAST:event_jComboBoxAcesoRapidoItemStateChanged

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        visaoUsuario.RegistrarAtiv reg = new visaoUsuario.RegistrarAtiv();
        reg.setVisible(true);
    }//GEN-LAST:event_jButtonRegistrarActionPerformed

    private void jLabelAlterSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAlterSenhaMouseClicked
        AlterarSenha altsenha = new AlterarSenha(jTextFieldUser.getText());
        altsenha.setVisible(true);
    }//GEN-LAST:event_jLabelAlterSenhaMouseClicked

    private void jButtonCadastrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrosActionPerformed
        CadACadastros cad = new CadACadastros();
        cad.setVisible(true);
    }//GEN-LAST:event_jButtonCadastrosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MirinsGrama;
    private javax.swing.JButton jButtonCadastros;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JButton jButtonRel;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSairAmeba;
    private javax.swing.JButton jButtonTabAux;
    private javax.swing.JComboBox<String> jComboBoxAcesoRapido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAlterSenha;
    private javax.swing.JLabel jLabelDesenvolvimentoMenu;
    private javax.swing.JLabel jLabelFaixaInfeior;
    private javax.swing.JLabel jLabelFaixaSuperior;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelLogoIMCG;
    private javax.swing.JLabel jLabelNameInst;
    private javax.swing.JLabel jLabelNameSetor;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JTextField jTextFieldNomeUser;
    private javax.swing.JTextField jTextFieldUser;
    // End of variables declaration//GEN-END:variables
}
