/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visaoUsuario;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import Beans.BeansDestinos;
import Beans.BeansRegistrarAtiv;
import Beans.BeansTabelas;
import modeloConection.ConexaoBD;
import modeloDao.DaoDestinos;
import modeloDao.DaoRegistarAtiv;
import controller.CampoNumerico;
import controller.LimiteDigitos;
import controller.UpperCase;

/**
 *
 * @author Professor
 */
public class RegistrarAtiv extends javax.swing.JFrame {

    ConexaoBD conex = new ConexaoBD();
    BeansRegistrarAtiv mod = new BeansRegistrarAtiv();
    DaoRegistarAtiv control = new DaoRegistarAtiv();    
    BeansDestinos modDest = new BeansDestinos();
    DaoDestinos controlDest = new DaoDestinos();
    
    int flag=0;
    int limite=8;
    int c=0; //flag para calcular distância da atividade
    
 
    public RegistrarAtiv() {
        
        initComponents();
        CbMotorista();
        CbAtividade();
        PreencherTabela("select b.id_regatividade,b.dtativ, a.nomemotorista, c.descricao as desc from tbl_motorista as a inner join tbl_reg_ativ as b "
                + "on (a.id_motorista = b.id_motorista) inner join tbl_tipoatividade c "
                + "on (b.id_tipoatividade = c.id_tipoatividade) order by id_regatividade desc");
        
        jTextFieldKmS.setDocument(new CampoNumerico());
        jTextFieldKmC.setDocument(new CampoNumerico());
        jTextFieldPlaca.setDocument(new LimiteDigitos());
        jTextFieldFuncionario.setDocument(new UpperCase());
        jTextFieldDestino.setDocument(new UpperCase());
        jButtonApagar.setEnabled(false);
        jButtonImprimir.setEnabled(false);
        jButtonEditar.setEnabled(false);
 
        jInternalFrameBuscaPlaca.setVisible(false);
        jInternalFrameBuscaDestino.setVisible(false);
        jLabelPlacaObr.setVisible(false);
        jLabelDataObr.setVisible(false);
        jLabelKCObr4.setVisible(false);
        jLabelKSObr3.setVisible(false);
        jLabelHrCObr.setVisible(false);
        jLabelHoraSObg.setVisible(false);
        jLabelDataObr.setVisible(false);
        jLabelDestObr.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrameBuscaPlaca = new javax.swing.JInternalFrame();
        jScrollPanePlaca = new javax.swing.JScrollPane();
        jTableBuscaVeiculo = new javax.swing.JTable();
        jButtonSairIF = new javax.swing.JButton();
        jButtonPesquisarIF = new javax.swing.JButton();
        jLabelFaixaMenu1 = new javax.swing.JLabel();
        JlabelFundoMenuIF = new javax.swing.JLabel();
        jInternalFrameBuscaDestino = new javax.swing.JInternalFrame();
        jScrollPaneDestino = new javax.swing.JScrollPane();
        jTableBuscaDestino = new javax.swing.JTable();
        jButtonSairIF1 = new javax.swing.JButton();
        jButtonPesquisarIF1 = new javax.swing.JButton();
        jLabelFaixaMenu2 = new javax.swing.JLabel();
        JlabelFundoMenuIF1 = new javax.swing.JLabel();
        jLabelMotorista = new javax.swing.JLabel();
        jComboBoxMotorista = new javax.swing.JComboBox();
        jLabelAtividade = new javax.swing.JLabel();
        jComboBoxAtividade = new javax.swing.JComboBox();
        jLabelSetorAtendido = new javax.swing.JLabel();
        jComboBoxListaSetor = new javax.swing.JComboBox();
        jLabelFuncionario = new javax.swing.JLabel();
        jTextFieldFuncionario = new javax.swing.JTextField();
        jLabelaData = new javax.swing.JLabel();
        jDateChooserdtativ = new com.toedter.calendar.JDateChooser();
        jLabelDataObr = new javax.swing.JLabel();
        jLabelPlaca = new javax.swing.JLabel();
        jLabelMarca = new javax.swing.JLabel();
        jTextFieldMarca = new javax.swing.JTextField();
        jTextFieldPlaca = new javax.swing.JTextField();
        jLabelPlacaObr = new javax.swing.JLabel();
        jButtonBuscarPlaca = new javax.swing.JButton();
        jLabelModelo = new javax.swing.JLabel();
        jTextFieldModelo = new javax.swing.JTextField();
        jScrollPaneVeiculo = new javax.swing.JScrollPane();
        jTableRegAtv = new javax.swing.JTable();
        jTextFieldKmS = new javax.swing.JTextField();
        jTextFieldKmC = new javax.swing.JTextField();
        jLabelKmS = new javax.swing.JLabel();
        jLabelKmC = new javax.swing.JLabel();
        jLabelHoraSObg = new javax.swing.JLabel();
        jLabelHrCObr = new javax.swing.JLabel();
        jLabelHrS = new javax.swing.JLabel();
        jLabelHrC = new javax.swing.JLabel();
        jFormattedTextFieldHrS = new javax.swing.JFormattedTextField();
        jFormattedTextFieldHrC = new javax.swing.JFormattedTextField();
        jLabelCod = new javax.swing.JLabel();
        jTextFieldCod = new javax.swing.JTextField();
        jLabelKSObr3 = new javax.swing.JLabel();
        jLabelKCObr4 = new javax.swing.JLabel();
        jLabelDestino = new javax.swing.JLabel();
        jTextFieldDestino = new javax.swing.JTextField();
        jButtonBuscarDest = new javax.swing.JButton();
        jButtonSalvaDestino = new javax.swing.JButton();
        jLabelDistancia = new javax.swing.JLabel();
        jTextFieldDistancia = new javax.swing.JTextField();
        jLabelDestObr = new javax.swing.JLabel();
        jButtonIncluir = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonApagar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jButtonPesquisar = new javax.swing.JButton();
        jButtonImprimir = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelFaixaMenu = new javax.swing.JLabel();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar Atividade");
        setResizable(false);
        getContentPane().setLayout(null);

        jInternalFrameBuscaPlaca.setTitle("Selecionar Veículo");
        jInternalFrameBuscaPlaca.setVisible(true);
        jInternalFrameBuscaPlaca.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableBuscaVeiculo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTableBuscaVeiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableBuscaVeiculo.setGridColor(new java.awt.Color(255, 255, 255));
        jTableBuscaVeiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableBuscaVeiculoMouseClicked(evt);
            }
        });
        jScrollPanePlaca.setViewportView(jTableBuscaVeiculo);

        jInternalFrameBuscaPlaca.getContentPane().add(jScrollPanePlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 470, 180));

        jButtonSairIF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/sair.png"))); // NOI18N
        jButtonSairIF.setToolTipText("Sair");
        jButtonSairIF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairIFActionPerformed(evt);
            }
        });
        jInternalFrameBuscaPlaca.getContentPane().add(jButtonSairIF, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 45, 30));

        jButtonPesquisarIF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/pesquisar.png"))); // NOI18N
        jButtonPesquisarIF.setToolTipText("Buscar");
        jButtonPesquisarIF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarIFActionPerformed(evt);
            }
        });
        jInternalFrameBuscaPlaca.getContentPane().add(jButtonPesquisarIF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 45, 30));

        jLabelFaixaMenu1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFaixaMenu1.setForeground(new java.awt.Color(102, 255, 255));
        jLabelFaixaMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menuprincipal_Faixa.png"))); // NOI18N
        jInternalFrameBuscaPlaca.getContentPane().add(jLabelFaixaMenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 30));

        JlabelFundoMenuIF.setBackground(new java.awt.Color(255, 255, 255));
        JlabelFundoMenuIF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menuprincipal_fundo.png"))); // NOI18N
        JlabelFundoMenuIF.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jInternalFrameBuscaPlaca.getContentPane().add(JlabelFundoMenuIF, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 10, 490, 220));

        getContentPane().add(jInternalFrameBuscaPlaca);
        jInternalFrameBuscaPlaca.setBounds(270, 70, 490, 240);

        jInternalFrameBuscaDestino.setTitle("Selecionar Destino");
        jInternalFrameBuscaDestino.setVisible(true);
        jInternalFrameBuscaDestino.getContentPane().setLayout(null);

        jTableBuscaDestino.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTableBuscaDestino.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableBuscaDestino.setGridColor(new java.awt.Color(255, 255, 255));
        jTableBuscaDestino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableBuscaDestinoMouseClicked(evt);
            }
        });
        jScrollPaneDestino.setViewportView(jTableBuscaDestino);

        jInternalFrameBuscaDestino.getContentPane().add(jScrollPaneDestino);
        jScrollPaneDestino.setBounds(0, 30, 470, 180);

        jButtonSairIF1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/sair.png"))); // NOI18N
        jButtonSairIF1.setToolTipText("Sair");
        jButtonSairIF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairIF1ActionPerformed(evt);
            }
        });
        jInternalFrameBuscaDestino.getContentPane().add(jButtonSairIF1);
        jButtonSairIF1.setBounds(60, 0, 45, 30);

        jButtonPesquisarIF1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/pesquisar.png"))); // NOI18N
        jButtonPesquisarIF1.setToolTipText("Buscar");
        jButtonPesquisarIF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarIF1ActionPerformed(evt);
            }
        });
        jInternalFrameBuscaDestino.getContentPane().add(jButtonPesquisarIF1);
        jButtonPesquisarIF1.setBounds(10, 0, 45, 30);

        jLabelFaixaMenu2.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFaixaMenu2.setForeground(new java.awt.Color(102, 255, 255));
        jLabelFaixaMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menuprincipal_Faixa.png"))); // NOI18N
        jInternalFrameBuscaDestino.getContentPane().add(jLabelFaixaMenu2);
        jLabelFaixaMenu2.setBounds(0, 0, 770, 30);

        JlabelFundoMenuIF1.setBackground(new java.awt.Color(255, 255, 255));
        JlabelFundoMenuIF1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menuprincipal_fundo.png"))); // NOI18N
        JlabelFundoMenuIF1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jInternalFrameBuscaDestino.getContentPane().add(JlabelFundoMenuIF1);
        JlabelFundoMenuIF1.setBounds(-10, 10, 490, 220);

        getContentPane().add(jInternalFrameBuscaDestino);
        jInternalFrameBuscaDestino.setBounds(0, 170, 490, 240);

        jLabelMotorista.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelMotorista.setText("Motorista:");
        getContentPane().add(jLabelMotorista);
        jLabelMotorista.setBounds(40, 70, 60, 25);

        jComboBoxMotorista.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBoxMotorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMotoristaActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxMotorista);
        jComboBoxMotorista.setBounds(100, 70, 300, 25);

        jLabelAtividade.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelAtividade.setText("Atividade:");
        getContentPane().add(jLabelAtividade);
        jLabelAtividade.setBounds(40, 100, 60, 25);

        jComboBoxAtividade.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(jComboBoxAtividade);
        jComboBoxAtividade.setBounds(100, 100, 300, 25);

        jLabelSetorAtendido.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelSetorAtendido.setText("Setor Atendido:");
        getContentPane().add(jLabelSetorAtendido);
        jLabelSetorAtendido.setBounds(10, 130, 90, 25);

        jComboBoxListaSetor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBoxListaSetor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECIONE", "ADMINISTRATIVO", "FINANCEIRO", "NÚCLEO DE TI", "NUTRIÇÃO", "PEDAGÓGICO", "PSICOLOGIA", "RECURSOS HUMANOS", "SERVIÇO SOCIAL" }));
        getContentPane().add(jComboBoxListaSetor);
        jComboBoxListaSetor.setBounds(100, 130, 300, 25);

        jLabelFuncionario.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelFuncionario.setText("Funcionário:");
        getContentPane().add(jLabelFuncionario);
        jLabelFuncionario.setBounds(30, 170, 70, 25);

        jTextFieldFuncionario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jTextFieldFuncionario);
        jTextFieldFuncionario.setBounds(100, 170, 300, 25);

        jLabelaData.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelaData.setText("Data:");
        getContentPane().add(jLabelaData);
        jLabelaData.setBounds(60, 250, 40, 25);

        jDateChooserdtativ.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jDateChooserdtativ.setMaxSelectableDate(new java.util.Date(253370779288000L));
        getContentPane().add(jDateChooserdtativ);
        jDateChooserdtativ.setBounds(100, 250, 140, 25);

        jLabelDataObr.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabelDataObr.setForeground(new java.awt.Color(255, 0, 0));
        jLabelDataObr.setText(" *");
        getContentPane().add(jLabelDataObr);
        jLabelDataObr.setBounds(60, 250, 20, 25);

        jLabelPlaca.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelPlaca.setText("Placa:");
        getContentPane().add(jLabelPlaca);
        jLabelPlaca.setBounds(410, 40, 40, 25);

        jLabelMarca.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelMarca.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelMarca.setText("Marca:");
        getContentPane().add(jLabelMarca);
        jLabelMarca.setBounds(630, 40, 50, 20);

        jTextFieldMarca.setEditable(false);
        jTextFieldMarca.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldMarca.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldMarca.setForeground(new java.awt.Color(51, 0, 255));
        jTextFieldMarca.setBorder(null);
        getContentPane().add(jTextFieldMarca);
        jTextFieldMarca.setBounds(680, 70, 130, 20);

        jTextFieldPlaca.setEditable(false);
        jTextFieldPlaca.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldPlaca.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextFieldPlaca.setMaximumSize(new java.awt.Dimension(8, 8));
        jTextFieldPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPlacaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldPlaca);
        jTextFieldPlaca.setBounds(450, 40, 130, 25);

        jLabelPlacaObr.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabelPlacaObr.setForeground(new java.awt.Color(255, 0, 0));
        jLabelPlacaObr.setText("*");
        getContentPane().add(jLabelPlacaObr);
        jLabelPlacaObr.setBounds(410, 40, 20, 20);

        jButtonBuscarPlaca.setBackground(new java.awt.Color(255, 255, 255));
        jButtonBuscarPlaca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/imgBuscar.png"))); // NOI18N
        jButtonBuscarPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarPlacaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscarPlaca);
        jButtonBuscarPlaca.setBounds(580, 40, 30, 25);

        jLabelModelo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelModelo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelModelo.setText("Modelo:");
        getContentPane().add(jLabelModelo);
        jLabelModelo.setBounds(620, 70, 60, 20);

        jTextFieldModelo.setEditable(false);
        jTextFieldModelo.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldModelo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldModelo.setForeground(new java.awt.Color(51, 0, 255));
        jTextFieldModelo.setBorder(null);
        jTextFieldModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldModeloActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldModelo);
        jTextFieldModelo.setBounds(680, 40, 130, 20);

        jTableRegAtv.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jTableRegAtv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableRegAtv.setGridColor(new java.awt.Color(255, 255, 255));
        jTableRegAtv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableRegAtvMouseClicked(evt);
            }
        });
        jScrollPaneVeiculo.setViewportView(jTableRegAtv);

        getContentPane().add(jScrollPaneVeiculo);
        jScrollPaneVeiculo.setBounds(410, 100, 460, 310);

        jTextFieldKmS.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldKmS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldKmSActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldKmS);
        jTextFieldKmS.setBounds(280, 290, 80, 25);

        jTextFieldKmC.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldKmC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldKmCActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldKmC);
        jTextFieldKmC.setBounds(280, 330, 80, 25);

        jLabelKmS.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelKmS.setText("Km. de Saída:");
        getContentPane().add(jLabelKmS);
        jLabelKmS.setBounds(190, 290, 90, 25);

        jLabelKmC.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelKmC.setText("Km. de Chegada:");
        getContentPane().add(jLabelKmC);
        jLabelKmC.setBounds(180, 330, 100, 25);

        jLabelHoraSObg.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabelHoraSObg.setForeground(new java.awt.Color(255, 0, 0));
        jLabelHoraSObg.setText("*");
        getContentPane().add(jLabelHoraSObg);
        jLabelHoraSObg.setBounds(20, 290, 20, 25);

        jLabelHrCObr.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabelHrCObr.setForeground(new java.awt.Color(255, 0, 0));
        jLabelHrCObr.setText("*");
        getContentPane().add(jLabelHrCObr);
        jLabelHrCObr.setBounds(0, 330, 20, 25);

        jLabelHrS.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelHrS.setText("Hr. de Saída:");
        getContentPane().add(jLabelHrS);
        jLabelHrS.setBounds(20, 290, 80, 25);

        jLabelHrC.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelHrC.setText("Hr. de Chegada:");
        getContentPane().add(jLabelHrC);
        jLabelHrC.setBounds(10, 330, 90, 25);

        try {
            jFormattedTextFieldHrS.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldHrS.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextFieldHrS.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jFormattedTextFieldHrS);
        jFormattedTextFieldHrS.setBounds(100, 290, 60, 25);

        try {
            jFormattedTextFieldHrC.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldHrC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextFieldHrC.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jFormattedTextFieldHrC);
        jFormattedTextFieldHrC.setBounds(100, 330, 60, 25);

        jLabelCod.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelCod.setText("Código:");
        getContentPane().add(jLabelCod);
        jLabelCod.setBounds(20, 40, 70, 25);

        jTextFieldCod.setEditable(false);
        jTextFieldCod.setEnabled(false);
        jTextFieldCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCod);
        jTextFieldCod.setBounds(100, 40, 60, 25);

        jLabelKSObr3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabelKSObr3.setForeground(new java.awt.Color(255, 0, 0));
        jLabelKSObr3.setText("  *");
        getContentPane().add(jLabelKSObr3);
        jLabelKSObr3.setBounds(190, 290, 20, 25);

        jLabelKCObr4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabelKCObr4.setForeground(new java.awt.Color(255, 0, 0));
        jLabelKCObr4.setText("  *");
        getContentPane().add(jLabelKCObr4);
        jLabelKCObr4.setBounds(170, 330, 20, 25);

        jLabelDestino.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelDestino.setText("Destino:");
        getContentPane().add(jLabelDestino);
        jLabelDestino.setBounds(30, 210, 70, 25);

        jTextFieldDestino.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jTextFieldDestino);
        jTextFieldDestino.setBounds(100, 210, 240, 25);

        jButtonBuscarDest.setBackground(new java.awt.Color(255, 255, 255));
        jButtonBuscarDest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/imgBuscar.png"))); // NOI18N
        jButtonBuscarDest.setToolTipText("Destinos Salvos");
        jButtonBuscarDest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarDestActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscarDest);
        jButtonBuscarDest.setBounds(340, 210, 30, 25);

        jButtonSalvaDestino.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSalvaDestino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/salvarMenor.png"))); // NOI18N
        jButtonSalvaDestino.setToolTipText("Salvar Destino");
        jButtonSalvaDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvaDestinoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvaDestino);
        jButtonSalvaDestino.setBounds(370, 210, 30, 25);

        jLabelDistancia.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelDistancia.setText("Km. Rodados na atividade:");
        getContentPane().add(jLabelDistancia);
        jLabelDistancia.setBounds(100, 370, 180, 25);

        jTextFieldDistancia.setEditable(false);
        jTextFieldDistancia.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldDistancia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldDistancia.setForeground(new java.awt.Color(255, 0, 51));
        jTextFieldDistancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDistanciaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldDistancia);
        jTextFieldDistancia.setBounds(280, 370, 80, 25);

        jLabelDestObr.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabelDestObr.setForeground(new java.awt.Color(255, 0, 0));
        jLabelDestObr.setText(" *");
        getContentPane().add(jLabelDestObr);
        jLabelDestObr.setBounds(50, 210, 20, 25);

        jButtonIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/incluir.png"))); // NOI18N
        jButtonIncluir.setToolTipText("Incluir");
        jButtonIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonIncluir);
        jButtonIncluir.setBounds(10, 0, 45, 30);

        jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/salvar.png"))); // NOI18N
        jButtonEditar.setToolTipText("Salvar");
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEditar);
        jButtonEditar.setBounds(60, 0, 45, 30);

        jButtonApagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/apagar.png"))); // NOI18N
        jButtonApagar.setToolTipText("Deletar");
        jButtonApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApagarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonApagar);
        jButtonApagar.setBounds(110, 0, 45, 30);

        jButtonLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/limpar.png"))); // NOI18N
        jButtonLimpar.setToolTipText("Limpar");
        jButtonLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonLimparMouseClicked(evt);
            }
        });
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLimpar);
        jButtonLimpar.setBounds(160, 0, 45, 30);

        jButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/pesquisar.png"))); // NOI18N
        jButtonPesquisar.setToolTipText("Buscar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPesquisar);
        jButtonPesquisar.setBounds(210, 0, 45, 30);

        jButtonImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/imprimir.png"))); // NOI18N
        jButtonImprimir.setToolTipText("Imprimir");
        jButtonImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImprimirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonImprimir);
        jButtonImprimir.setBounds(260, 0, 45, 30);

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/sair.png"))); // NOI18N
        jButtonSair.setToolTipText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSair);
        jButtonSair.setBounds(310, 0, 45, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("* Campos de preenchimento obrigatório.");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 400, 220, 14);

        jLabelFaixaMenu.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFaixaMenu.setForeground(new java.awt.Color(102, 255, 255));
        jLabelFaixaMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menuprincipal_Faixa.png"))); // NOI18N
        getContentPane().add(jLabelFaixaMenu);
        jLabelFaixaMenu.setBounds(0, 0, 900, 30);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menuprincipal_fundo.png"))); // NOI18N
        getContentPane().add(jLabelFundo);
        jLabelFundo.setBounds(-20, 20, 930, 400);

        setSize(new java.awt.Dimension(886, 450));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void CbMotorista(){
    
        conex.conexao();
        conex.executaSql("select *from tbl_motorista where status=true order by nomemotorista");
        try{
            conex.rs.first();
            jComboBoxMotorista.removeAllItems();
            do{
                jComboBoxMotorista.addItem(conex.rs.getString("nomemotorista").toUpperCase());
            }while(conex.rs.next());
        
        
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(rootPane, "Registre os motoristas da empresa no menu Cadastro de Motorista");
            //RegistrarAtiv.this.dispose();
            }
        }
    
    public void CbAtividade(){
    
        conex.conexao();
        conex.executaSql("select *from tbl_tipoatividade order by descricao");
        try{
            conex.rs.first();
            jComboBoxAtividade.removeAllItems();
            do{
                jComboBoxAtividade.addItem(conex.rs.getString("descricao").toUpperCase());
            }while(conex.rs.next());
        
        
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(rootPane, "Registre os tipos de atividades da empresa nas Tabelas Aux");
            //RegistrarAtiv.this.dispose();
            }
        }

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLimparMouseClicked
    
    jTextFieldFuncionario.setText("");
    jTextFieldModelo.setText("");
    jTextFieldMarca.setText("");
    jTextFieldPlaca.setText("");
    jTextFieldKmS.setText("");
    jTextFieldKmC.setText("");
    jFormattedTextFieldHrS.setText("");
    jFormattedTextFieldHrC.setText("");
    jTextFieldCod.setText("");
    jTextFieldDestino.setText("");
    jTextFieldDistancia.setText("");
    jDateChooserdtativ.setDate(null);
    jButtonApagar.setEnabled(false);
    jButtonEditar.setEnabled(false);
    jButtonIncluir.setEnabled(true);
    jLabelDataObr.setVisible(false);
    jLabelPlacaObr.setVisible(false);
    jLabelKCObr4.setVisible(false);
    jLabelKSObr3.setVisible(false);
    jLabelHrCObr.setVisible(false);
    jLabelHoraSObg.setVisible(false);

    }//GEN-LAST:event_jButtonLimparMouseClicked

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jTextFieldModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldModeloActionPerformed
       
    }//GEN-LAST:event_jTextFieldModeloActionPerformed

    private void jTextFieldKmSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldKmSActionPerformed
        
    }//GEN-LAST:event_jTextFieldKmSActionPerformed

    private void jButtonIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirActionPerformed
            
        if(jTextFieldPlaca.getText().isEmpty()
        || jDateChooserdtativ.getDate() == null
        || jTextFieldKmS.getText().isEmpty()
        || jTextFieldKmC.getText().isEmpty()
        || Integer.valueOf(jTextFieldKmC.getText()) < Integer.valueOf(jTextFieldKmS.getText())
        || jFormattedTextFieldHrC.getText().equals("  :  ")
        || jFormattedTextFieldHrS.getText().equals("  :  ")){

            
        if(jTextFieldKmC.getText().isEmpty() || Integer.valueOf(jTextFieldKmC.getText()) < Integer.valueOf(jTextFieldKmS.getText()) ) {            
        jTextFieldKmC.requestFocus();
        jLabelKCObr4.setVisible(true);
        JOptionPane.showMessageDialog(null, "Campo Obrigatório\nE a quilometragem de chegada deve ser maior que a quilometragem de saida");
        }
        else{
        jLabelKCObr4.setVisible(false);
        }
        if(jFormattedTextFieldHrC.getText().equals("  :  ")){
        jFormattedTextFieldHrC.requestFocus();
        jLabelHrCObr.setVisible(true);
        }else{
        jLabelHrCObr.setVisible(false);
        }
        if(jTextFieldKmS.getText().isEmpty()){
        jTextFieldKmS.requestFocus();
        jLabelKSObr3.setVisible(true); 
        }else{
        jLabelKSObr3.setVisible(false);        
        }
        if (jFormattedTextFieldHrS.getText().equals("  :  ")) {
        jLabelHoraSObg.setVisible(true);
        jFormattedTextFieldHrS.requestFocus();
        }else{
        jLabelHoraSObg.setVisible(false);
        }
        if (jDateChooserdtativ.getDate() == null){
        jDateChooserdtativ.requestFocusInWindow();
        jLabelDataObr.setVisible(true);
        }else{
        jLabelDataObr.setVisible(false);
        //mod.setDtativ(jDateChooserdtativ.getDate());
        }        
        if(jTextFieldPlaca.getText().isEmpty()){
        jLabelPlacaObr.setVisible(true);
        jTextFieldPlaca.requestFocus();
        }else{
        jLabelPlacaObr.setVisible(false);
        }
             
    }else{
    
    mod.setPlaca(jTextFieldPlaca.getText());
    mod.setDtativ(jDateChooserdtativ.getDate());
    mod.setKmsaida(Integer.parseInt(jTextFieldKmS.getText()));
    mod.setKmchegada(Integer.parseInt(jTextFieldKmC.getText()));
    mod.setHrsaida(jFormattedTextFieldHrS.getText());
    mod.setHrchegada(jFormattedTextFieldHrC.getText());            
    mod.setNomemotorista((String) jComboBoxMotorista.getSelectedItem());
    mod.setAtividade((String) jComboBoxAtividade.getSelectedItem());
    mod.setSetoratendido((String)jComboBoxListaSetor.getSelectedItem());
    mod.setFuncionario(jTextFieldFuncionario.getText());
    mod.setDestino(jTextFieldDestino.getText());
    
    c = Integer.valueOf(jTextFieldKmC.getText()) - Integer.valueOf(jTextFieldKmS.getText());
    mod.setDistancia(c);
    
    control.Salvar(mod);

    
    
    jTextFieldFuncionario.setText("");
    jTextFieldModelo.setText("");
    jTextFieldMarca.setText("");
    jTextFieldPlaca.setText("");
    jTextFieldKmS.setText("");
    jTextFieldKmC.setText("");
    jFormattedTextFieldHrS.setText("");
    jFormattedTextFieldHrC.setText("");
    jTextFieldCod.setText("");
    jTextFieldDestino.setText("");
    jTextFieldDistancia.setText("");
    jDateChooserdtativ.setDate(null);
    jButtonApagar.setEnabled(false);
    jButtonEditar.setEnabled(false);
    jButtonIncluir.setEnabled(true);
    jLabelDataObr.setVisible(false);
    jLabelPlacaObr.setVisible(false);
    jLabelDataObr.setVisible(false);
    jLabelKCObr4.setVisible(false);
    jLabelKSObr3.setVisible(false);
}
    
    PreencherTabela("select b.id_regatividade, b.dtativ, a.nomemotorista, c.descricao as desc from tbl_motorista as a inner join tbl_reg_ativ as b "
                + "on (a.id_motorista = b.id_motorista) inner join tbl_tipoatividade c "
                + "on (b.id_tipoatividade = c.id_tipoatividade) order by id_regatividade desc"); 
    }//GEN-LAST:event_jButtonIncluirActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
               
     
        if(jTextFieldPlaca.getText().isEmpty()
        || jDateChooserdtativ.getDate() == null
        || jTextFieldKmS.getText().isEmpty()
        || jTextFieldKmC.getText().isEmpty()
        || Integer.valueOf(jTextFieldKmC.getText()) < Integer.valueOf(jTextFieldKmS.getText())
        || jFormattedTextFieldHrC.getText().equals("  :  ")
        || jFormattedTextFieldHrS.getText().equals("  :  ")){

            
        if(jTextFieldKmC.getText().isEmpty() || Integer.valueOf(jTextFieldKmC.getText()) < Integer.valueOf(jTextFieldKmS.getText()) ) {            
        jTextFieldKmC.requestFocus();
        jLabelKCObr4.setVisible(true);
        JOptionPane.showMessageDialog(null, "Campo Obrigatório\nE a quilometragem de chegada deve ser maior que a quilometragem de saida");
        }
        else{
        jLabelKCObr4.setVisible(false);
        }
        if(jFormattedTextFieldHrC.getText().equals("  :  ")){
        jFormattedTextFieldHrC.requestFocus();
        jLabelHrCObr.setVisible(true);
        }else{
        jLabelHrCObr.setVisible(false);
        }
        if(jTextFieldKmS.getText().isEmpty()){
        jTextFieldKmS.requestFocus();
        jLabelKSObr3.setVisible(true); 
        }else{
        jLabelKSObr3.setVisible(false);        
        }
        if (jFormattedTextFieldHrS.getText().equals("  :  ")) {
        jLabelHoraSObg.setVisible(true);
        jFormattedTextFieldHrS.requestFocus();
        }else{
        jLabelHoraSObg.setVisible(false);
        }
        if (jDateChooserdtativ.getDate() == null){
        jDateChooserdtativ.requestFocusInWindow();
        jLabelDataObr.setVisible(true);
        }else{
        jLabelDataObr.setVisible(false);
        //mod.setDtativ(jDateChooserdtativ.getDate());
        }        
        if(jTextFieldPlaca.getText().isEmpty()){
        jLabelPlacaObr.setVisible(true);
        jTextFieldPlaca.requestFocus();
        }else{
        jLabelPlacaObr.setVisible(false);
        }
             
    }else{
    
    mod.setPlaca(jTextFieldPlaca.getText());
    mod.setDtativ(jDateChooserdtativ.getDate());
    mod.setKmsaida(Integer.parseInt(jTextFieldKmS.getText()));
    mod.setKmchegada(Integer.parseInt(jTextFieldKmC.getText()));
    mod.setHrsaida(jFormattedTextFieldHrS.getText());
    mod.setHrchegada(jFormattedTextFieldHrC.getText());            
    mod.setNomemotorista((String) jComboBoxMotorista.getSelectedItem());
    mod.setAtividade((String) jComboBoxAtividade.getSelectedItem());
    mod.setSetoratendido((String)jComboBoxListaSetor.getSelectedItem());
    mod.setFuncionario(jTextFieldFuncionario.getText());
    mod.setDestino(jTextFieldDestino.getText());
    c = Integer.valueOf(jTextFieldKmC.getText()) - Integer.valueOf(jTextFieldKmS.getText());
    mod.setDistancia(c);
    control.Editar(mod);

    
    jTextFieldFuncionario.setText("");
    jTextFieldModelo.setText("");
    jTextFieldMarca.setText("");
    jTextFieldPlaca.setText("");
    jTextFieldKmS.setText("");
    jTextFieldKmC.setText("");
    jFormattedTextFieldHrS.setText("");
    jFormattedTextFieldHrC.setText("");
    jTextFieldCod.setText("");
    jTextFieldDestino.setText("");
    jTextFieldDistancia.setText("");
    jDateChooserdtativ.setDate(null);
    jButtonApagar.setEnabled(false);
    jButtonEditar.setEnabled(false);
    jButtonIncluir.setEnabled(true);
    jLabelDataObr.setVisible(false);
    jLabelPlacaObr.setVisible(false);
    jLabelDataObr.setVisible(false);
    jLabelKCObr4.setVisible(false);
    jLabelKSObr3.setVisible(false);
}
    
    PreencherTabela("select b.id_regatividade, b.dtativ, a.nomemotorista, c.descricao as desc from tbl_motorista as a inner join tbl_reg_ativ as b "
                + "on (a.id_motorista = b.id_motorista) inner join tbl_tipoatividade c "
                + "on (b.id_tipoatividade = c.id_tipoatividade) order by id_regatividade desc"); 
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApagarActionPerformed
 
            int Confirm = JOptionPane.showConfirmDialog(null,"Excluir registro?"," Excluir", JOptionPane.YES_NO_OPTION);
            if (Confirm == JOptionPane.YES_OPTION) {
            mod.setCodigo(Integer.parseInt(jTextFieldCod.getText()));
            control.Excluir(mod);  
            
            PreencherTabela("select b.id_regatividade, b.dtativ, a.nomemotorista, c.descricao as desc from tbl_motorista as a inner join tbl_reg_ativ as b "
                            + "on (a.id_motorista = b.id_motorista) inner join tbl_tipoatividade c "
                            + "on (b.id_tipoatividade = c.id_tipoatividade) order by id_regatividade desc");
            
            jTextFieldCod.setText("");
            jTextFieldFuncionario.setText("");
            jTextFieldModelo.setText("");
            jTextFieldMarca.setText("");
            jTextFieldPlaca.setText("");
            jTextFieldKmS.setText("");
            jTextFieldKmC.setText("");
            jFormattedTextFieldHrS.setText("");
            jFormattedTextFieldHrC.setText("");
            jTextFieldDestino.setText("");
            jDateChooserdtativ.setDate(null);   
            
            jButtonApagar.setEnabled(false);
            jButtonEditar.setEnabled(false);
            jButtonIncluir.setEnabled(true);
            
            }else if (Confirm == JOptionPane.NO_OPTION){
                setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                }        
    }//GEN-LAST:event_jButtonApagarActionPerformed

    private void jTextFieldCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodActionPerformed
      
    }//GEN-LAST:event_jTextFieldCodActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed

    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonBuscarPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarPlacaActionPerformed
        PreencherTabelaIF("select a.placa, b.descricao, c.descricaomarca as desc from tbl_veiculo as a inner join tbl_modelo as b "
                + "on (a.id_modelo = b.id_modelo) inner join tbl_marca c "
                + "on (b.id_marca = c.id_marca) where ativo=true");
        jInternalFrameBuscaPlaca.setVisible(true);
        jInternalFrameBuscaDestino.setVisible(false);

    }//GEN-LAST:event_jButtonBuscarPlacaActionPerformed

    private void jComboBoxMotoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMotoristaActionPerformed
        
    }//GEN-LAST:event_jComboBoxMotoristaActionPerformed

    private void jButtonImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImprimirActionPerformed
        
    }//GEN-LAST:event_jButtonImprimirActionPerformed

    private void jTableRegAtvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableRegAtvMouseClicked
       String cod = ""+jTableRegAtv.getValueAt(jTableRegAtv.getSelectedRow(), 0);
       jFormattedTextFieldHrS.setText("");
       jFormattedTextFieldHrC.setText("");
        int i = Integer.parseInt(cod);
        
        mod.setCodigo(i); 
        BeansRegistrarAtiv model = control.PesquisarReg(mod);
        control.PesquisarReg(mod);
        
            jTextFieldCod.setText(String.valueOf(model.getCodigo()));
            jComboBoxMotorista.setSelectedItem(model.getNomemotorista());
            jComboBoxAtividade.setSelectedItem(model.getAtividade());
            jComboBoxListaSetor.setSelectedItem(model.getSetoratendido());
            jTextFieldPlaca.setText(model.getPlaca());
            jTextFieldFuncionario.setText(model.getFuncionario());
            jTextFieldKmS.setText(String.valueOf(model.getKmsaida()));
            jTextFieldKmC.setText(String.valueOf(model.getKmchegada()));
            jDateChooserdtativ.setDate(model.getDtativ());
            jFormattedTextFieldHrS.setText(model.getHrsaida());
            jFormattedTextFieldHrC.setText(model.getHrchegada());
            jTextFieldModelo.setText(model.getModelo());
            jTextFieldMarca.setText(model.getMarca());
            jTextFieldDestino.setText(model.getDestino());
            jTextFieldDistancia.setText(String.valueOf(model.getDistancia()));
        jButtonIncluir.setEnabled(false);
        //jButtonEditar.setEnabled(true);
        //jButtonApagar.setEnabled(true);    
    }//GEN-LAST:event_jTableRegAtvMouseClicked

    private void jTextFieldPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPlacaActionPerformed
       
    }//GEN-LAST:event_jTextFieldPlacaActionPerformed

    private void jTextFieldKmCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldKmCActionPerformed

    }//GEN-LAST:event_jTextFieldKmCActionPerformed

    private void jTableBuscaVeiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableBuscaVeiculoMouseClicked
            String cod = ""+jTableBuscaVeiculo.getValueAt(jTableBuscaVeiculo.getSelectedRow(), 0);

            mod.setPlaca(cod);
            BeansRegistrarAtiv model = control.Pesquisar(mod);
            jTextFieldPlaca.setText(model.getPlaca());
            //condição para preenchimento dos campos 
            jTextFieldMarca.setText(model.getMarca());
            jTextFieldModelo.setText(model.getModelo());

            jInternalFrameBuscaPlaca.setVisible(false);
            

    }//GEN-LAST:event_jTableBuscaVeiculoMouseClicked

    private void jButtonSairIFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairIFActionPerformed
        jInternalFrameBuscaPlaca.dispose();
    }//GEN-LAST:event_jButtonSairIFActionPerformed

    private void jButtonPesquisarIFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarIFActionPerformed
      PreencherTabelaIF("select a.placa, b.descricao, c.descricaomarca as desc from tbl_veiculo as a inner join tbl_modelo as b "
                + "on (a.id_modelo = b.id_modelo) inner join tbl_marca c "
                + "on (b.id_marca = c.id_marca) where ativo=true");

    }//GEN-LAST:event_jButtonPesquisarIFActionPerformed

    private void jTextFieldDistanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDistanciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDistanciaActionPerformed

    private void jButtonBuscarDestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarDestActionPerformed
        PreencherTabelaDestinoIF("select id_destino, descricao from tbl_destinos");
        jInternalFrameBuscaDestino.setVisible(true);
        jInternalFrameBuscaPlaca.dispose();
    }//GEN-LAST:event_jButtonBuscarDestActionPerformed

    private void jButtonSalvaDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvaDestinoActionPerformed
        if(jTextFieldDestino.getText().isEmpty()){
            jTextFieldDestino.requestFocus();
            jLabelDestObr.setVisible(true);
        }else{
            jLabelDestObr.setVisible(false);
            modDest.setDescricao(jTextFieldDestino.getText());
            controlDest.Salvar(modDest);
        }
    }//GEN-LAST:event_jButtonSalvaDestinoActionPerformed

    private void jTableBuscaDestinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableBuscaDestinoMouseClicked
        String cod = ""+jTableBuscaDestino.getValueAt(jTableBuscaDestino.getSelectedRow(), 1);

        modDest.setDescricao(cod);
        controlDest.Pesquisar(modDest);
        jTextFieldDestino.setText(modDest.getDescricao());
        jInternalFrameBuscaDestino.dispose();
    }//GEN-LAST:event_jTableBuscaDestinoMouseClicked

    private void jButtonSairIF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairIF1ActionPerformed
        jInternalFrameBuscaDestino.dispose();
    }//GEN-LAST:event_jButtonSairIF1ActionPerformed

    private void jButtonPesquisarIF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarIF1ActionPerformed
        PreencherTabelaDestinoIF("select id_destino, descricao from tbl_destinos");

    }//GEN-LAST:event_jButtonPesquisarIF1ActionPerformed


     public void PreencherTabela(String SQL){
      ArrayList dados = new ArrayList();
      String[] colunas = new String[]{"","","",""};
      
      conex.conexao();
      conex.executaSql(SQL);

      try{
          conex.rs.first();       
          do{
              dados.add(new Object[]{conex.rs.getInt("id_regatividade"),
                                     conex.rs.getDate("dtativ"),
                                     //conex.rs.getDate("dtativ",Calendar.getInstance(Locale.CHINA) ),
                                     conex.rs.getString("nomemotorista"),
                                     conex.rs.getString("desc")
                                    });
 
          }while(conex.rs.next());
      
        }catch(SQLException ex){
          //JOptionPane.showMessageDialog(rootPane, "Erro ao preencher ArrayList\nErro:"+ex); 
        }
      
      BeansTabelas modelo = new BeansTabelas(dados, colunas);
      
      jTableRegAtv.setModel(modelo);
      jTableRegAtv.getColumnModel().getColumn(0).setPreferredWidth(30);
      jTableRegAtv.getColumnModel().getColumn(0).setResizable(false);
      jTableRegAtv.getColumnModel().getColumn(0).setHeaderValue("ID");
      jTableRegAtv.getColumnModel().getColumn(1).setPreferredWidth(60);
      jTableRegAtv.getColumnModel().getColumn(1).setResizable(false); //não redimensionaveL
      jTableRegAtv.getColumnModel().getColumn(1).setHeaderValue("DATA");
      jTableRegAtv.getColumnModel().getColumn(2).setPreferredWidth(110);
      jTableRegAtv.getColumnModel().getColumn(2).setResizable(false);
      jTableRegAtv.getColumnModel().getColumn(2).setHeaderValue("MOTORISTA");
      jTableRegAtv.getColumnModel().getColumn(3).setPreferredWidth(237);
      jTableRegAtv.getColumnModel().getColumn(3).setResizable(false);
      jTableRegAtv.getColumnModel().getColumn(3).setHeaderValue("ATIVIDADE");

      jTableRegAtv.getTableHeader().setReorderingAllowed(false); //não reordenavel
      jTableRegAtv.setAutoResizeMode(jTableRegAtv.AUTO_RESIZE_OFF); //não redmencionar
      jTableRegAtv.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);//selicioar um dado por vez
    }
     
    public void PreencherTabelaIF(String SQL){
      ArrayList dados = new ArrayList();
      String[] colunas = new String[]{"PLACA","MARCA","MODELO"};
      
      conex.conexao();
      conex.executaSql(SQL);

      try{
          conex.rs.first();       
          do{
              dados.add(new Object[]{conex.rs.getString("placa"),
                                     conex.rs.getString("desc"),
                                     conex.rs.getString("descricao")
                                     
                                    });
 
          }while(conex.rs.next());
      
        }catch(SQLException ex){
          JOptionPane.showMessageDialog(rootPane, "Erro ao preencher ArrayList\nErro:"+ex);
        }
      
      BeansTabelas bv = new BeansTabelas(dados, colunas);
      
      jTableBuscaVeiculo.setModel(bv);
      jTableBuscaVeiculo.getColumnModel().getColumn(0).setPreferredWidth(40);
      jTableBuscaVeiculo.getColumnModel().getColumn(0).setResizable(false);
      jTableBuscaVeiculo.getColumnModel().getColumn(0).setHeaderValue("PLACA");
      jTableBuscaVeiculo.getColumnModel().getColumn(1).setPreferredWidth(60);
      jTableBuscaVeiculo.getColumnModel().getColumn(1).setResizable(false); //não redimensionaveL
      jTableBuscaVeiculo.getColumnModel().getColumn(1).setHeaderValue("MARCA");
      jTableBuscaVeiculo.getColumnModel().getColumn(2).setPreferredWidth(110);
      jTableBuscaVeiculo.getColumnModel().getColumn(2).setResizable(false);
      jTableBuscaVeiculo.getColumnModel().getColumn(2).setHeaderValue("MODELO");
      

      jTableRegAtv.getTableHeader().setReorderingAllowed(false); //não reordenavel
      jTableRegAtv.setAutoResizeMode(jTableRegAtv.AUTO_RESIZE_OFF); //não redmencionar
      jTableRegAtv.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);//selicioar um dado por vez
    } 
    
    public void PreencherTabelaDestinoIF(String SQL){
      ArrayList dados = new ArrayList();
      String[] colunas = new String[]{"ID","DESTINO"};
      
      conex.conexao();
      conex.executaSql(SQL);

      try{
          conex.rs.first();       
          do{
              dados.add(new Object[]{conex.rs.getString("id_destino"),
                                     conex.rs.getString("descricao")
                                     
                                     
                                    });
 
          }while(conex.rs.next());
      
        }catch(SQLException ex){
          JOptionPane.showMessageDialog(rootPane, "Erro ao preencher ArrayList\nErro:"+ex);
        }
      
      BeansTabelas bv = new BeansTabelas(dados, colunas);
      
      jTableBuscaDestino.setModel(bv);
      jTableBuscaDestino.getColumnModel().getColumn(0).setPreferredWidth(10);
      jTableBuscaDestino.getColumnModel().getColumn(0).setResizable(false);
      jTableBuscaDestino.getColumnModel().getColumn(0).setHeaderValue("ID");
      jTableBuscaDestino.getColumnModel().getColumn(1).setPreferredWidth(430);
      jTableBuscaDestino.getColumnModel().getColumn(1).setResizable(false); //não redimensionaveL
      jTableBuscaDestino.getColumnModel().getColumn(1).setHeaderValue("DESTINO");
      
      

      jTableRegAtv.getTableHeader().setReorderingAllowed(false); //não reordenavel
      jTableRegAtv.setAutoResizeMode(jTableBuscaDestino.AUTO_RESIZE_OFF); //não redmencionar
      jTableRegAtv.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);//selicioar um dado por vez
    } 
      
    
    
 
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPadrao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPadrao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPadrao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPadrao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new janelaPadrao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JlabelFundoMenuIF;
    private javax.swing.JLabel JlabelFundoMenuIF1;
    private javax.swing.JButton jButtonApagar;
    private javax.swing.JButton jButtonBuscarDest;
    private javax.swing.JButton jButtonBuscarPlaca;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonImprimir;
    private javax.swing.JButton jButtonIncluir;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonPesquisarIF;
    private javax.swing.JButton jButtonPesquisarIF1;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSairIF;
    private javax.swing.JButton jButtonSairIF1;
    private javax.swing.JButton jButtonSalvaDestino;
    public javax.swing.JComboBox jComboBoxAtividade;
    private javax.swing.JComboBox jComboBoxListaSetor;
    private javax.swing.JComboBox jComboBoxMotorista;
    private com.toedter.calendar.JDateChooser jDateChooserdtativ;
    private javax.swing.JFormattedTextField jFormattedTextFieldHrC;
    private javax.swing.JFormattedTextField jFormattedTextFieldHrS;
    private javax.swing.JInternalFrame jInternalFrameBuscaDestino;
    private javax.swing.JInternalFrame jInternalFrameBuscaPlaca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAtividade;
    private javax.swing.JLabel jLabelCod;
    private javax.swing.JLabel jLabelDataObr;
    private javax.swing.JLabel jLabelDestObr;
    private javax.swing.JLabel jLabelDestino;
    private javax.swing.JLabel jLabelDistancia;
    private javax.swing.JLabel jLabelFaixaMenu;
    private javax.swing.JLabel jLabelFaixaMenu1;
    private javax.swing.JLabel jLabelFaixaMenu2;
    private javax.swing.JLabel jLabelFuncionario;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelHoraSObg;
    private javax.swing.JLabel jLabelHrC;
    private javax.swing.JLabel jLabelHrCObr;
    private javax.swing.JLabel jLabelHrS;
    private javax.swing.JLabel jLabelKCObr4;
    private javax.swing.JLabel jLabelKSObr3;
    private javax.swing.JLabel jLabelKmC;
    private javax.swing.JLabel jLabelKmS;
    private javax.swing.JLabel jLabelMarca;
    private javax.swing.JLabel jLabelModelo;
    private javax.swing.JLabel jLabelMotorista;
    private javax.swing.JLabel jLabelPlaca;
    private javax.swing.JLabel jLabelPlacaObr;
    private javax.swing.JLabel jLabelSetorAtendido;
    private javax.swing.JLabel jLabelaData;
    private javax.swing.JScrollPane jScrollPaneDestino;
    private javax.swing.JScrollPane jScrollPanePlaca;
    private javax.swing.JScrollPane jScrollPaneVeiculo;
    private javax.swing.JTable jTableBuscaDestino;
    private javax.swing.JTable jTableBuscaVeiculo;
    private javax.swing.JTable jTableRegAtv;
    private javax.swing.JTextField jTextFieldCod;
    private javax.swing.JTextField jTextFieldDestino;
    private javax.swing.JTextField jTextFieldDistancia;
    private javax.swing.JTextField jTextFieldFuncionario;
    private javax.swing.JTextField jTextFieldKmC;
    private javax.swing.JTextField jTextFieldKmS;
    private javax.swing.JTextField jTextFieldMarca;
    private javax.swing.JTextField jTextFieldModelo;
    public javax.swing.JTextField jTextFieldPlaca;
    // End of variables declaration//GEN-END:variables
}
