/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visaoUsuario;

import visaoMaster.TbDestinos;
import visaoMaster.*;

/**
 *
 * @author Professor
 */
public class TbATabelasAuxiliares extends javax.swing.JFrame {

    /**
     * Creates new form janelaPadrao
     */
    public TbATabelasAuxiliares() {
        initComponents();
        jLabelMarca.setEnabled(false);
        jLabelModelo.setEnabled(false);
        jLabelAtividade.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelDestino = new javax.swing.JLabel();
        jLabelMarca = new javax.swing.JLabel();
        jLabelModelo = new javax.swing.JLabel();
        jLabelAtividade = new javax.swing.JLabel();
        jButtonSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelFaixaMenu = new javax.swing.JLabel();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tabelas Auxiliares");
        setResizable(false);
        getContentPane().setLayout(null);

        jLabelDestino.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelDestino.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDestino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/IconMenuInterno.png"))); // NOI18N
        jLabelDestino.setText("Destinos");
        jLabelDestino.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelDestino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDestinoMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDestino);
        jLabelDestino.setBounds(440, 50, 120, 90);

        jLabelMarca.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMarca.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMarca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/IconMenuInterno.png"))); // NOI18N
        jLabelMarca.setText("Marca");
        jLabelMarca.setEnabled(false);
        jLabelMarca.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelMarca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMarcaMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelMarca);
        jLabelMarca.setBounds(50, 50, 120, 90);

        jLabelModelo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelModelo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelModelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/IconMenuInterno.png"))); // NOI18N
        jLabelModelo.setText("Modelo");
        jLabelModelo.setEnabled(false);
        jLabelModelo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelModelo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelModeloMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelModelo);
        jLabelModelo.setBounds(180, 50, 120, 90);

        jLabelAtividade.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelAtividade.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAtividade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/IconMenuInterno.png"))); // NOI18N
        jLabelAtividade.setText("Atividade");
        jLabelAtividade.setEnabled(false);
        jLabelAtividade.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelAtividade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAtividadeMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelAtividade);
        jLabelAtividade.setBounds(310, 50, 120, 90);

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/sair.png"))); // NOI18N
        jButtonSair.setToolTipText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSair);
        jButtonSair.setBounds(520, 0, 45, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Selecione um menu");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 190, 120, 14);

        jLabelFaixaMenu.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFaixaMenu.setForeground(new java.awt.Color(102, 255, 255));
        jLabelFaixaMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menuprincipal_Faixa.png"))); // NOI18N
        getContentPane().add(jLabelFaixaMenu);
        jLabelFaixaMenu.setBounds(0, 0, 580, 30);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menuprincipal_fundo.png"))); // NOI18N
        getContentPane().add(jLabelFundo);
        jLabelFundo.setBounds(0, 30, 580, 180);

        setSize(new java.awt.Dimension(577, 242));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
    dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jLabelDestinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDestinoMouseClicked
         visaoUsuario.Destinos dest = new visaoUsuario.Destinos();
         dest.setVisible(true);
         dispose();
    }//GEN-LAST:event_jLabelDestinoMouseClicked

    private void jLabelMarcaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMarcaMouseClicked
        //Marca marca = new Marca();
        //marca.setVisible(true);
       // dispose();
    }//GEN-LAST:event_jLabelMarcaMouseClicked

    private void jLabelModeloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelModeloMouseClicked
        //Modelo modelo = new Modelo();
       // modelo.setVisible(true);
       // dispose();
    }//GEN-LAST:event_jLabelModeloMouseClicked

    private void jLabelAtividadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAtividadeMouseClicked
        
    }//GEN-LAST:event_jLabelAtividadeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPadrao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPadrao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPadrao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPadrao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPadrao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAtividade;
    private javax.swing.JLabel jLabelDestino;
    private javax.swing.JLabel jLabelFaixaMenu;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelMarca;
    private javax.swing.JLabel jLabelModelo;
    // End of variables declaration//GEN-END:variables
}
