/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visaoMaster;

/**
 *
 * @author Professor
 */
public class CadACadastros extends javax.swing.JFrame {

    /**
     * Creates new form janelaPadrao
     */
    public CadACadastros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMotorista = new javax.swing.JLabel();
        Veiculos = new javax.swing.JLabel();
        Usuarios = new javax.swing.JLabel();
        jButtonSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelFaixaMenu = new javax.swing.JLabel();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastros");
        setResizable(false);
        getContentPane().setLayout(null);

        jLabelMotorista.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMotorista.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMotorista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/IconMenuInterno.png"))); // NOI18N
        jLabelMotorista.setText("Motoristas");
        jLabelMotorista.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelMotorista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMotoristaMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelMotorista);
        jLabelMotorista.setBounds(50, 60, 120, 90);

        Veiculos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Veiculos.setForeground(new java.awt.Color(255, 255, 255));
        Veiculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/IconMenuInterno.png"))); // NOI18N
        Veiculos.setText("Veículos");
        Veiculos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Veiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VeiculosMouseClicked(evt);
            }
        });
        getContentPane().add(Veiculos);
        Veiculos.setBounds(180, 60, 120, 90);

        Usuarios.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Usuarios.setForeground(new java.awt.Color(255, 255, 255));
        Usuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/IconMenuInterno.png"))); // NOI18N
        Usuarios.setText("Usuários");
        Usuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UsuariosMouseClicked(evt);
            }
        });
        getContentPane().add(Usuarios);
        Usuarios.setBounds(310, 60, 120, 90);

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/sair.png"))); // NOI18N
        jButtonSair.setToolTipText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSair);
        jButtonSair.setBounds(450, 0, 45, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("* Campos de preenchimento obrigatório.");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 180, 220, 14);

        jLabelFaixaMenu.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFaixaMenu.setForeground(new java.awt.Color(102, 255, 255));
        jLabelFaixaMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menuprincipal_Faixa.png"))); // NOI18N
        getContentPane().add(jLabelFaixaMenu);
        jLabelFaixaMenu.setBounds(0, 0, 500, 30);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menuprincipal_fundo.png"))); // NOI18N
        getContentPane().add(jLabelFundo);
        jLabelFundo.setBounds(0, 30, 500, 180);

        setSize(new java.awt.Dimension(505, 241));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jLabelMotoristaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMotoristaMouseClicked
        CadMotorista motorista = new CadMotorista();
        motorista.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabelMotoristaMouseClicked

    private void VeiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VeiculosMouseClicked
        CadVeiculos veiculo = new CadVeiculos();
        veiculo.setVisible(true);
        dispose();
    }//GEN-LAST:event_VeiculosMouseClicked

    private void UsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsuariosMouseClicked
        CadUsuarios cadU = new CadUsuarios();
        cadU.setVisible(true);
        dispose();
    }//GEN-LAST:event_UsuariosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPadrao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPadrao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPadrao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPadrao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPadrao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Usuarios;
    private javax.swing.JLabel Veiculos;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFaixaMenu;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelMotorista;
    // End of variables declaration//GEN-END:variables
}
