/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visaoMaster;

import java.io.File;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.filechooser.FileNameExtensionFilter;
import Beans.BeansCadMotorista;
import Beans.BeansTabelas;
import modeloConection.ConexaoBD;
import modeloDao.DaoCadMotorista;
import controller.CampoNumerico;
import controller.UpperCase;
import java.text.SimpleDateFormat;
import java.util.Date;

public class CadMotorista extends javax.swing.JFrame {

    BeansCadMotorista mod = new BeansCadMotorista();
    DaoCadMotorista control = new DaoCadMotorista();
    ConexaoBD conex = new ConexaoBD();
    int flag=1;
 
    public CadMotorista() {
        initComponents();
        jButtonEditar.setEnabled(false);
        jButtonApagar.setEnabled(false);
        jButtonImprimir.setEnabled(false);
        jTextFieldVinc.setDocument(new CampoNumerico());
        jTextFieldMat.setDocument(new CampoNumerico()); 
        jTextFieldNun.setDocument(new CampoNumerico());
        jTextFieldRegProf.setDocument(new CampoNumerico());
        jTextFieldNome.setDocument(new UpperCase());
        jTextFieldLog.setDocument(new UpperCase());
        jTextFieldComp.setDocument(new UpperCase());
        jTextFieldBairro.setDocument(new UpperCase());
        jInternalFrameBuscaMotorista.setVisible(false);
    }

    /**1
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrameBuscaMotorista = new javax.swing.JInternalFrame();
        jScrollPaneMarca = new javax.swing.JScrollPane();
        jTableMotorista = new javax.swing.JTable();
        jButtonSairIF = new javax.swing.JButton();
        jButtonPesquisarIF = new javax.swing.JButton();
        jLabelFaixaMenu1 = new javax.swing.JLabel();
        JlabelFundoMenuIF = new javax.swing.JLabel();
        jLabelCod = new javax.swing.JLabel();
        jTextFieldCod = new javax.swing.JTextField();
        jLabelBuscaImagem = new javax.swing.JLabel();
        jButtonDeletaImagem = new javax.swing.JButton();
        jButtonInsereimagem = new javax.swing.JButton();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jComboBoxSexo = new javax.swing.JComboBox();
        jLabelSexo = new javax.swing.JLabel();
        jLabelEscolaridade = new javax.swing.JLabel();
        jComboBoxEscolaridade = new javax.swing.JComboBox();
        jLabelHabilitacao = new javax.swing.JLabel();
        jCheckBoxA = new javax.swing.JCheckBox();
        jCheckBoxB = new javax.swing.JCheckBox();
        jCheckBoxC = new javax.swing.JCheckBox();
        jCheckBoxD = new javax.swing.JCheckBox();
        jCheckBoxE = new javax.swing.JCheckBox();
        jLabelDtNasc = new javax.swing.JLabel();
        jLabelDtEnt = new javax.swing.JLabel();
        jLabelDtSai = new javax.swing.JLabel();
        jDateChooserDtNasc = new com.toedter.calendar.JDateChooser();
        jDateChooserDtEnt = new com.toedter.calendar.JDateChooser();
        jDateChooserDtSai = new com.toedter.calendar.JDateChooser();
        jLabelRgProfissional = new javax.swing.JLabel();
        jTextFieldRegProf = new javax.swing.JTextField();
        jLabelMatVinc = new javax.swing.JLabel();
        jTextFieldMat = new javax.swing.JTextField();
        jLabelSepMatVinc = new javax.swing.JLabel();
        jTextFieldVinc = new javax.swing.JTextField();
        jComboBoxTipVinc = new javax.swing.JComboBox();
        jLabelTipVin = new javax.swing.JLabel();
        jLabelLog = new javax.swing.JLabel();
        jTextFieldLog = new javax.swing.JTextField();
        jLabelRgCep = new javax.swing.JLabel();
        jFormattedTextFieldCep = new javax.swing.JFormattedTextField();
        jLabelNun = new javax.swing.JLabel();
        jTextFieldNun = new javax.swing.JTextField();
        jLabelComp = new javax.swing.JLabel();
        jTextFieldComp = new javax.swing.JTextField();
        jLabelBairro = new javax.swing.JLabel();
        jTextFieldBairro = new javax.swing.JTextField();
        jLabelCel = new javax.swing.JLabel();
        jFormattedTextFieldCel = new javax.swing.JFormattedTextField();
        jLabelFone = new javax.swing.JLabel();
        jFormattedTextFieldFone = new javax.swing.JFormattedTextField();
        jCheckBoxMotoristaAtivar = new javax.swing.JCheckBox();
        jButtonIncluir = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonApagar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jButtonPesquisar = new javax.swing.JButton();
        jButtonImprimir = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelFaixaMenu = new javax.swing.JLabel();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Motorista");
        setResizable(false);
        getContentPane().setLayout(null);

        jInternalFrameBuscaMotorista.setTitle("Selecionar Motorista");
        jInternalFrameBuscaMotorista.setVisible(true);
        jInternalFrameBuscaMotorista.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableMotorista.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableMotorista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableMotorista.setGridColor(new java.awt.Color(255, 255, 255));
        jTableMotorista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMotoristaMouseClicked(evt);
            }
        });
        jScrollPaneMarca.setViewportView(jTableMotorista);

        jInternalFrameBuscaMotorista.getContentPane().add(jScrollPaneMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 520, 250));

        jButtonSairIF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/sair.png"))); // NOI18N
        jButtonSairIF.setToolTipText("Sair");
        jButtonSairIF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairIFActionPerformed(evt);
            }
        });
        jInternalFrameBuscaMotorista.getContentPane().add(jButtonSairIF, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 45, 30));

        jButtonPesquisarIF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/pesquisar.png"))); // NOI18N
        jButtonPesquisarIF.setToolTipText("Buscar");
        jButtonPesquisarIF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarIFActionPerformed(evt);
            }
        });
        jInternalFrameBuscaMotorista.getContentPane().add(jButtonPesquisarIF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 45, 30));

        jLabelFaixaMenu1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFaixaMenu1.setForeground(new java.awt.Color(102, 255, 255));
        jLabelFaixaMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menuprincipal_Faixa.png"))); // NOI18N
        jInternalFrameBuscaMotorista.getContentPane().add(jLabelFaixaMenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 30));

        JlabelFundoMenuIF.setBackground(new java.awt.Color(255, 255, 255));
        JlabelFundoMenuIF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menuprincipal_fundo.png"))); // NOI18N
        JlabelFundoMenuIF.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jInternalFrameBuscaMotorista.getContentPane().add(JlabelFundoMenuIF, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 10, 600, 330));

        getContentPane().add(jInternalFrameBuscaMotorista);
        jInternalFrameBuscaMotorista.setBounds(120, 40, 530, 310);

        jLabelCod.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelCod.setText("Código:");
        getContentPane().add(jLabelCod);
        jLabelCod.setBounds(107, 40, 60, 25);

        jTextFieldCod.setEditable(false);
        jTextFieldCod.setEnabled(false);
        jTextFieldCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCod);
        jTextFieldCod.setBounds(180, 40, 60, 25);

        jLabelBuscaImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/semfoto.png"))); // NOI18N
        jLabelBuscaImagem.setToolTipText("Foto");
        getContentPane().add(jLabelBuscaImagem);
        jLabelBuscaImagem.setBounds(20, 40, 90, 80);

        jButtonDeletaImagem.setBackground(new java.awt.Color(255, 255, 255));
        jButtonDeletaImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/deletefoto.png"))); // NOI18N
        jButtonDeletaImagem.setToolTipText("Remover Foto");
        jButtonDeletaImagem.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(jButtonDeletaImagem);
        jButtonDeletaImagem.setBounds(20, 120, 50, 40);

        jButtonInsereimagem.setBackground(new java.awt.Color(255, 255, 255));
        jButtonInsereimagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/inserefoto.png"))); // NOI18N
        jButtonInsereimagem.setToolTipText("Inserir Foto");
        jButtonInsereimagem.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonInsereimagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsereimagemActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonInsereimagem);
        jButtonInsereimagem.setBounds(70, 120, 50, 40);

        jLabelNome.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelNome.setText("Nome:");
        getContentPane().add(jLabelNome);
        jLabelNome.setBounds(130, 70, 40, 25);

        jTextFieldNome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jTextFieldNome);
        jTextFieldNome.setBounds(180, 70, 520, 25);

        jComboBoxSexo.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jComboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECIONE", "FEMININO", "MASCULINO" }));
        jComboBoxSexo.setToolTipText("");
        getContentPane().add(jComboBoxSexo);
        jComboBoxSexo.setBounds(180, 110, 130, 25);

        jLabelSexo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelSexo.setText("Sexo:");
        getContentPane().add(jLabelSexo);
        jLabelSexo.setBounds(130, 110, 40, 25);

        jLabelEscolaridade.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelEscolaridade.setText("Escolaridade:");
        getContentPane().add(jLabelEscolaridade);
        jLabelEscolaridade.setBounds(380, 110, 80, 25);

        jComboBoxEscolaridade.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jComboBoxEscolaridade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECIONE", "ENSINO FUNDAMENTAL INCOMPLETO", "ENSINO FUNDAMENTAL COMPLETO", "ENSINO MÉDIO INCOMPLETO", "ENSINO MÉDIO COMPLETO", "ENSINO SUPERIO INCOMPLETO", "ENSINO SUPERIOR COMPLETO", "PÓS-GRADUAÇÃO" }));
        getContentPane().add(jComboBoxEscolaridade);
        jComboBoxEscolaridade.setBounds(460, 110, 240, 25);

        jLabelHabilitacao.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelHabilitacao.setText("Habilitação: ");
        getContentPane().add(jLabelHabilitacao);
        jLabelHabilitacao.setBounds(170, 140, 70, 25);

        jCheckBoxA.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxA.setText("A");
        getContentPane().add(jCheckBoxA);
        jCheckBoxA.setBounds(240, 140, 35, 25);

        jCheckBoxB.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxB.setText("B");
        getContentPane().add(jCheckBoxB);
        jCheckBoxB.setBounds(280, 140, 35, 25);

        jCheckBoxC.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxC.setText("C");
        jCheckBoxC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxCActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBoxC);
        jCheckBoxC.setBounds(320, 140, 35, 25);

        jCheckBoxD.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxD.setText("D");
        getContentPane().add(jCheckBoxD);
        jCheckBoxD.setBounds(360, 140, 35, 25);

        jCheckBoxE.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxE.setText("E");
        getContentPane().add(jCheckBoxE);
        jCheckBoxE.setBounds(400, 140, 35, 25);

        jLabelDtNasc.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelDtNasc.setText("Dt. Nascimento:");
        getContentPane().add(jLabelDtNasc);
        jLabelDtNasc.setBounds(70, 170, 90, 25);

        jLabelDtEnt.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelDtEnt.setText("Dt. Entrada:");
        getContentPane().add(jLabelDtEnt);
        jLabelDtEnt.setBounds(300, 170, 70, 25);

        jLabelDtSai.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelDtSai.setText("Dt. Saída:");
        getContentPane().add(jLabelDtSai);
        jLabelDtSai.setBounds(510, 170, 60, 25);

        jDateChooserDtNasc.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        getContentPane().add(jDateChooserDtNasc);
        jDateChooserDtNasc.setBounds(160, 170, 130, 25);

        jDateChooserDtEnt.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        getContentPane().add(jDateChooserDtEnt);
        jDateChooserDtEnt.setBounds(370, 170, 130, 25);

        jDateChooserDtSai.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        getContentPane().add(jDateChooserDtSai);
        jDateChooserDtSai.setBounds(570, 170, 130, 25);

        jLabelRgProfissional.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelRgProfissional.setText("Registro Profissional:");
        getContentPane().add(jLabelRgProfissional);
        jLabelRgProfissional.setBounds(10, 210, 120, 25);

        jTextFieldRegProf.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jTextFieldRegProf);
        jTextFieldRegProf.setBounds(140, 210, 90, 25);

        jLabelMatVinc.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelMatVinc.setText("Matrícula / Vinc");
        getContentPane().add(jLabelMatVinc);
        jLabelMatVinc.setBounds(230, 210, 90, 25);

        jTextFieldMat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jTextFieldMat);
        jTextFieldMat.setBounds(320, 210, 50, 25);

        jLabelSepMatVinc.setText("/");
        getContentPane().add(jLabelSepMatVinc);
        jLabelSepMatVinc.setBounds(370, 210, 10, 25);

        jTextFieldVinc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jTextFieldVinc);
        jTextFieldVinc.setBounds(380, 210, 50, 25);

        jComboBoxTipVinc.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jComboBoxTipVinc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECIONE", "COMISSIONADO", "CONCURSADO", "CLT", "ESTÁGIO", "PRESTAÇÃO DE SERVIÇO" }));
        getContentPane().add(jComboBoxTipVinc);
        jComboBoxTipVinc.setBounds(530, 210, 170, 25);

        jLabelTipVin.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelTipVin.setText("Tipo de Vínculo:");
        getContentPane().add(jLabelTipVin);
        jLabelTipVin.setBounds(440, 210, 90, 25);

        jLabelLog.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelLog.setText("Logradouro:");
        getContentPane().add(jLabelLog);
        jLabelLog.setBounds(230, 250, 70, 25);

        jTextFieldLog.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jTextFieldLog);
        jTextFieldLog.setBounds(300, 250, 270, 25);

        jLabelRgCep.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelRgCep.setText("Cep:");
        getContentPane().add(jLabelRgCep);
        jLabelRgCep.setBounds(90, 250, 40, 25);

        try {
            jFormattedTextFieldCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCep.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextFieldCep.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jFormattedTextFieldCep);
        jFormattedTextFieldCep.setBounds(140, 250, 90, 25);

        jLabelNun.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelNun.setText("Número:");
        getContentPane().add(jLabelNun);
        jLabelNun.setBounds(590, 250, 50, 25);

        jTextFieldNun.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jTextFieldNun);
        jTextFieldNun.setBounds(640, 250, 60, 25);

        jLabelComp.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelComp.setText("Complemento:");
        getContentPane().add(jLabelComp);
        jLabelComp.setBounds(40, 290, 90, 25);

        jTextFieldComp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jTextFieldComp);
        jTextFieldComp.setBounds(140, 290, 260, 25);

        jLabelBairro.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelBairro.setText("Bairro:");
        getContentPane().add(jLabelBairro);
        jLabelBairro.setBounds(410, 290, 40, 25);

        jTextFieldBairro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jTextFieldBairro);
        jTextFieldBairro.setBounds(450, 290, 250, 25);

        jLabelCel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelCel.setText("Celular:");
        getContentPane().add(jLabelCel);
        jLabelCel.setBounds(70, 330, 50, 25);

        try {
            jFormattedTextFieldCel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)9####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jFormattedTextFieldCel);
        jFormattedTextFieldCel.setBounds(140, 330, 130, 25);

        jLabelFone.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelFone.setText("Fone:");
        getContentPane().add(jLabelFone);
        jLabelFone.setBounds(280, 330, 40, 25);

        try {
            jFormattedTextFieldFone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldFone.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jFormattedTextFieldFone);
        jFormattedTextFieldFone.setBounds(320, 330, 140, 25);

        jCheckBoxMotoristaAtivar.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxMotoristaAtivar.setText("Trabalhando?");
        jCheckBoxMotoristaAtivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMotoristaAtivarActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBoxMotoristaAtivar);
        jCheckBoxMotoristaAtivar.setBounds(610, 40, 110, 23);

        jButtonIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/incluir.png"))); // NOI18N
        jButtonIncluir.setToolTipText("Incluir");
        jButtonIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonIncluir);
        jButtonIncluir.setBounds(10, 0, 45, 30);

        jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/salvar.png"))); // NOI18N
        jButtonEditar.setToolTipText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEditar);
        jButtonEditar.setBounds(60, 0, 45, 30);

        jButtonApagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/apagar.png"))); // NOI18N
        jButtonApagar.setToolTipText("Deletar");
        jButtonApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApagarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonApagar);
        jButtonApagar.setBounds(110, 0, 45, 30);

        jButtonLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/limpar.png"))); // NOI18N
        jButtonLimpar.setToolTipText("Limpar");
        jButtonLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonLimparMouseClicked(evt);
            }
        });
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLimpar);
        jButtonLimpar.setBounds(160, 0, 45, 30);

        jButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/pesquisar.png"))); // NOI18N
        jButtonPesquisar.setToolTipText("Buscar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPesquisar);
        jButtonPesquisar.setBounds(210, 0, 45, 30);

        jButtonImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/imprimir.png"))); // NOI18N
        jButtonImprimir.setToolTipText("Imprimir");
        getContentPane().add(jButtonImprimir);
        jButtonImprimir.setBounds(260, 0, 45, 30);

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/sair.png"))); // NOI18N
        jButtonSair.setToolTipText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSair);
        jButtonSair.setBounds(310, 0, 45, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("* Campos de preenchimento obrigatório.");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 360, 220, 14);

        jLabelFaixaMenu.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFaixaMenu.setForeground(new java.awt.Color(102, 255, 255));
        jLabelFaixaMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menuprincipal_Faixa.png"))); // NOI18N
        getContentPane().add(jLabelFaixaMenu);
        jLabelFaixaMenu.setBounds(0, 0, 770, 30);

        jLabelFundo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menuprincipal_fundo.png"))); // NOI18N
        jLabelFundo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(jLabelFundo);
        jLabelFundo.setBounds(0, 30, 790, 360);

        setSize(new java.awt.Dimension(753, 415));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        CadACadastros cad = new CadACadastros();
        cad.setVisible(true);
        dispose();        
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLimparMouseClicked
    jTextFieldCod.setText(null);
    jTextFieldBairro.setText(null);
    jFormattedTextFieldCep.setText(null);
    jTextFieldComp.setText(null);
    jTextFieldLog.setText(null);
    jTextFieldMat.setText(null);
    jTextFieldNome.setText(null);
    jTextFieldNun.setText(null);
    jTextFieldRegProf.setText(null);
    jTextFieldVinc.setText(null);
    jDateChooserDtNasc.setDate(null);
    jDateChooserDtEnt.setDate(null);
    jDateChooserDtSai.setDate(null);
    jCheckBoxA.setSelected(false);
    jCheckBoxB.setSelected(false);
    jCheckBoxC.setSelected(false);
    jCheckBoxD.setSelected(false);
    jCheckBoxE.setSelected(false);
    jCheckBoxMotoristaAtivar.setSelected(false);
    jFormattedTextFieldCel.setText("");
    jFormattedTextFieldFone.setText("");
    jButtonApagar.setEnabled(false);
    jButtonEditar.setEnabled(false);
    jButtonIncluir.setEnabled(true); 
    }//GEN-LAST:event_jButtonLimparMouseClicked

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jCheckBoxCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxCActionPerformed
        
    }//GEN-LAST:event_jCheckBoxCActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
       
        mod.setNomemotorista(jTextFieldNome.getText());
        mod.setSexo((String)(jComboBoxSexo.getSelectedItem()));
        mod.setEscolaridade((String)(jComboBoxEscolaridade.getSelectedItem()));
        mod.setHaba(jCheckBoxA.isSelected());
        mod.setHabb(jCheckBoxB.isSelected());
        mod.setHabc(jCheckBoxC.isSelected());
        mod.setHabd(jCheckBoxD.isSelected());
        mod.setHabe(jCheckBoxE.isSelected());
        mod.setRegprofissional(Integer.parseInt(jTextFieldRegProf.getText()));
        mod.setMatricula(Integer.parseInt(jTextFieldMat.getText()));
        mod.setVinculo(Integer.parseInt(jTextFieldVinc.getText()));
        mod.setTipovinculo((String)(jComboBoxTipVinc.getSelectedItem()));
        mod.setCep(jFormattedTextFieldCep.getText());
        mod.setLogradouro(jTextFieldLog.getText());
        mod.setNumero(Integer.parseInt(jTextFieldNun.getText()));
        mod.setComplemento(jTextFieldComp.getText());
        mod.setBairro(jTextFieldBairro.getText());
        mod.setTelefone(jFormattedTextFieldFone.getText());
        mod.setCelular(jFormattedTextFieldCel.getText());
        mod.setDtnasc(jDateChooserDtNasc.getDate());
        mod.setDtent(jDateChooserDtEnt.getDate());
        mod.setDtsai(jDateChooserDtSai.getDate());
        mod.setStatus(jCheckBoxMotoristaAtivar.isSelected());
       control.Editar(mod);
       jButtonIncluir.setEnabled(false);
      
        
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirActionPerformed
        
        mod.setNomemotorista(jTextFieldNome.getText());
        mod.setSexo((String) jComboBoxSexo.getSelectedItem());
        mod.setHaba(jCheckBoxA.isSelected());
        mod.setHabb(jCheckBoxB.isSelected());
        mod.setHabc(jCheckBoxC.isSelected());
        mod.setHabd(jCheckBoxD.isSelected());
        mod.setRegprofissional(Integer.parseInt(jTextFieldRegProf.getText()));
        mod.setMatricula(Integer.parseInt(jTextFieldMat.getText()));
        mod.setVinculo(Integer.parseInt(jTextFieldVinc.getText()));
        mod.setCep(jFormattedTextFieldCep.getText());
        mod.setLogradouro(jTextFieldLog.getText());
        mod.setNumero(Integer.parseInt(jTextFieldNun.getText()));
        mod.setComplemento(jTextFieldComp.getText());
        mod.setBairro(jTextFieldBairro.getText());
        mod.setTelefone(jFormattedTextFieldFone.getText());
        mod.setCelular(jFormattedTextFieldCel.getText());
        mod.setEscolaridade((String)jComboBoxEscolaridade.getSelectedItem());
        mod.setTipovinculo((String)jComboBoxTipVinc.getSelectedItem());
        mod.setDtnasc(jDateChooserDtNasc.getDate());
        mod.setDtent(jDateChooserDtEnt.getDate());
      //mod.setDtsai(jDateChooserDtSai.getDate());
        mod.setStatus(jCheckBoxMotoristaAtivar.isSelected());
        
        
        control.Salvar(mod);
        
        mod.setNomemotorista(jTextFieldNome.getText());
        BeansCadMotorista model = control.Pesquisar(mod);
        jTextFieldCod.setText(String.valueOf(model.getCodigo()));
        
        jButtonIncluir.setEnabled(false);
        jButtonEditar.setEnabled(true);
        jButtonApagar.setEnabled(true);

    }//GEN-LAST:event_jButtonIncluirActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
     PreencherTabelaIF("select id_motorista, nomemotorista from tbl_motorista order by nomemotorista");
     jInternalFrameBuscaMotorista.setVisible(true);
       /*
        
     */
        
      
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jTextFieldCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodActionPerformed
        
    }//GEN-LAST:event_jTextFieldCodActionPerformed

    private void jButtonApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApagarActionPerformed
        if(flag==1){
            int Confirm = JOptionPane.showConfirmDialog(null,"Excluir registro?"," Excluir", JOptionPane.YES_NO_OPTION);
                if (Confirm == JOptionPane.YES_OPTION) {
                mod.setCodigo(Integer.parseInt(jTextFieldCod.getText()));
                mod.setNomemotorista(jTextFieldNome.getText());
                control.Excluir(mod); 
                jTextFieldCod.setText(null);
                jTextFieldBairro.setText(null);
                jFormattedTextFieldCep.setText(null);
                jTextFieldComp.setText(null);
                jTextFieldLog.setText(null);
                jTextFieldMat.setText(null);
                jTextFieldNome.setText(null);
                jTextFieldNun.setText(null);
                jTextFieldRegProf.setText(null);
                jTextFieldVinc.setText(null);
                jDateChooserDtNasc.setDate(null);
                jDateChooserDtEnt.setDate(null);
                jDateChooserDtSai.setDate(null);
                jCheckBoxA.setSelected(false);
                jCheckBoxB.setSelected(false);
                jCheckBoxC.setSelected(false);
                jCheckBoxD.setSelected(false);
                jCheckBoxE.setSelected(false);
                jFormattedTextFieldCel.setText("");
                jFormattedTextFieldFone.setText("");
                jButtonApagar.setEnabled(false);
                jButtonEditar.setEnabled(false);
                jButtonIncluir.setEnabled(true);

                }else if (Confirm == JOptionPane.NO_OPTION){
                setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                }
         }
        else{
            int Confirm = JOptionPane.showConfirmDialog(null,"Excluir registro?"," Excluir", JOptionPane.YES_NO_OPTION);
                if (Confirm == JOptionPane.YES_OPTION) {
                mod.setCodigo(Integer.parseInt(jTextFieldCod.getText()));
                mod.setNomemotorista(jTextFieldNome.getText());
                control.Excluir(mod);       
                }else if (Confirm == JOptionPane.NO_OPTION){
                setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                }
        }
    }//GEN-LAST:event_jButtonApagarActionPerformed

    private void jButtonInsereimagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsereimagemActionPerformed
        
        JFileChooser fileChosChooser = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("*.jpg", "jpg");
        String diretorioBase = System.getProperty("users.Joelson+")+"/Desktop";
        File dir = new File(diretorioBase);
        fileChosChooser.setCurrentDirectory(dir);

        fileChosChooser.setFileFilter(filtro);

        int resposta = fileChosChooser.showOpenDialog(new JDialog());
        
        File file = new File("");
        
        if(resposta == JFileChooser.APPROVE_OPTION){
                file = fileChosChooser.getSelectedFile();
                JOptionPane.showMessageDialog(null, "Arquivo selecionado com Sucesso");
         
        }else if(resposta == JFileChooser.CANCEL_OPTION){
            JOptionPane.showMessageDialog(null, "Cancelado");
                        
        }
    }//GEN-LAST:event_jButtonInsereimagemActionPerformed

    private void jCheckBoxMotoristaAtivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMotoristaAtivarActionPerformed
        
    }//GEN-LAST:event_jCheckBoxMotoristaAtivarActionPerformed

    private void jTableMotoristaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMotoristaMouseClicked
        String descricaomarca = ""+jTableMotorista.getValueAt(jTableMotorista.getSelectedRow(), 1);
        mod.setPesquisar(descricaomarca);
        BeansCadMotorista model = control.Pesquisar(mod);
        
        jTextFieldCod.setText(String.valueOf(model.getCodigo()));
        jTextFieldNome.setText(model.getNomemotorista());
        jComboBoxSexo.setSelectedItem(model.getSexo());
        jTextFieldBairro.setText(model.getBairro()) ;
        jTextFieldComp.setText(model.getComplemento());
        jTextFieldLog.setText(model.getLogradouro());
        jTextFieldMat.setText(String.valueOf(model.getMatricula()));
        jTextFieldNun.setText(String.valueOf(model.getNumero())); 
        jTextFieldRegProf.setText(String.valueOf(model.getRegprofissional()));
        jTextFieldVinc.setText(String.valueOf(model.getVinculo()));
        jFormattedTextFieldCel.setText(String.valueOf(model.getCelular()));
        jFormattedTextFieldCep.setText(String.valueOf(model.getCep()));
        jFormattedTextFieldFone.setText(String.valueOf(model.getTelefone()));
        jComboBoxEscolaridade.setSelectedItem(model.getEscolaridade());
        jComboBoxTipVinc.setSelectedItem(model.getTipovinculo());
        jCheckBoxA.setSelected(model.isHaba());
        jCheckBoxB.setSelected(model.isHabb());
        jCheckBoxC.setSelected(model.isHabc());
        jCheckBoxD.setSelected(model.isHabd());
        jCheckBoxE.setSelected(model.isHabe());
        jDateChooserDtNasc.setDate(model.getDtnasc());
        jDateChooserDtEnt.setDate(model.getDtent());
        jDateChooserDtSai.setDate(model.getDtsai());
        jCheckBoxMotoristaAtivar.setSelected(model.isStatus());
     
        jButtonEditar.setEnabled(true);
        jButtonApagar.setEnabled(true);
        jButtonIncluir.setEnabled(false);

        conex.desconecta();
        jInternalFrameBuscaMotorista.dispose();
        
    }//GEN-LAST:event_jTableMotoristaMouseClicked

    private void jButtonSairIFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairIFActionPerformed
        jInternalFrameBuscaMotorista.dispose();
    }//GEN-LAST:event_jButtonSairIFActionPerformed

    private void jButtonPesquisarIFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarIFActionPerformed
        PreencherTabelaIF("select id_motorista, nomemotorista from tbl_motorista order by nomemotorista");
    }//GEN-LAST:event_jButtonPesquisarIFActionPerformed

    
    public void PreencherTabelaIF(String SQL){
      ArrayList dados = new ArrayList();
      String[] colunas = new String[]{"",""};
      
      conex.conexao();
      conex.executaSql(SQL);

      try{
          conex.rs.first();       
          do{
              dados.add(new Object[]{conex.rs.getInt("id_motorista"),
                                     conex.rs.getString("nomemotorista")
                                   
                                    });
 
          }while(conex.rs.next());
      
        }catch(SQLException ex){
          JOptionPane.showMessageDialog(null, "Erro ao preencher ArrayList\nErro:"+ex);
        }
          
     BeansTabelas modelo = new BeansTabelas(dados, colunas);
      
     jTableMotorista.setModel(modelo);
     jTableMotorista.getColumnModel().getColumn(0).setPreferredWidth(45);
     jTableMotorista.getColumnModel().getColumn(0).setResizable(true);
     jTableMotorista.getColumnModel().getColumn(0).setHeaderValue("COD");
     jTableMotorista.getColumnModel().getColumn(1).setPreferredWidth(450);
     jTableMotorista.getColumnModel().getColumn(1).setResizable(true); //não redimensionaveL
     jTableMotorista.getColumnModel().getColumn(1).setHeaderValue("NOME");
           

     jTableMotorista.getTableHeader().setReorderingAllowed(false); //não reordenavel
     jTableMotorista.setAutoResizeMode(jTableMotorista.AUTO_RESIZE_OFF); //não redmencionar
     jTableMotorista.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);//selicioar um dado por vez
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPadrao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPadrao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPadrao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPadrao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPadrao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JlabelFundoMenuIF;
    private javax.swing.JButton jButtonApagar;
    private javax.swing.JButton jButtonDeletaImagem;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonImprimir;
    private javax.swing.JButton jButtonIncluir;
    private javax.swing.JButton jButtonInsereimagem;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonPesquisarIF;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSairIF;
    private javax.swing.JCheckBox jCheckBoxA;
    private javax.swing.JCheckBox jCheckBoxB;
    private javax.swing.JCheckBox jCheckBoxC;
    private javax.swing.JCheckBox jCheckBoxD;
    private javax.swing.JCheckBox jCheckBoxE;
    private javax.swing.JCheckBox jCheckBoxMotoristaAtivar;
    private javax.swing.JComboBox jComboBoxEscolaridade;
    private javax.swing.JComboBox jComboBoxSexo;
    private javax.swing.JComboBox jComboBoxTipVinc;
    private com.toedter.calendar.JDateChooser jDateChooserDtEnt;
    private com.toedter.calendar.JDateChooser jDateChooserDtNasc;
    private com.toedter.calendar.JDateChooser jDateChooserDtSai;
    private javax.swing.JFormattedTextField jFormattedTextFieldCel;
    private javax.swing.JFormattedTextField jFormattedTextFieldCep;
    private javax.swing.JFormattedTextField jFormattedTextFieldFone;
    private javax.swing.JInternalFrame jInternalFrameBuscaMotorista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelBairro;
    private javax.swing.JLabel jLabelBuscaImagem;
    private javax.swing.JLabel jLabelCel;
    private javax.swing.JLabel jLabelCod;
    private javax.swing.JLabel jLabelComp;
    private javax.swing.JLabel jLabelDtEnt;
    private javax.swing.JLabel jLabelDtNasc;
    private javax.swing.JLabel jLabelDtSai;
    private javax.swing.JLabel jLabelEscolaridade;
    private javax.swing.JLabel jLabelFaixaMenu;
    private javax.swing.JLabel jLabelFaixaMenu1;
    private javax.swing.JLabel jLabelFone;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelHabilitacao;
    private javax.swing.JLabel jLabelLog;
    private javax.swing.JLabel jLabelMatVinc;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNun;
    private javax.swing.JLabel jLabelRgCep;
    private javax.swing.JLabel jLabelRgProfissional;
    private javax.swing.JLabel jLabelSepMatVinc;
    private javax.swing.JLabel jLabelSexo;
    private javax.swing.JLabel jLabelTipVin;
    private javax.swing.JScrollPane jScrollPaneMarca;
    private javax.swing.JTable jTableMotorista;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldCod;
    private javax.swing.JTextField jTextFieldComp;
    private javax.swing.JTextField jTextFieldLog;
    private javax.swing.JTextField jTextFieldMat;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldNun;
    private javax.swing.JTextField jTextFieldRegProf;
    private javax.swing.JTextField jTextFieldVinc;
    // End of variables declaration//GEN-END:variables
}
