/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visaoMaster;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import Beans.BeansTabelas;
import Beans.BeansVeiculo;
import modeloConection.ConexaoBD;
import modeloDao.DaoVeiculo;
import controller.CampoNumerico;
import controller.LimiteDigitos;
import controller.UpperCase;


public class CadVeiculos extends javax.swing.JFrame {

   BeansVeiculo mod = new BeansVeiculo();
   DaoVeiculo control = new DaoVeiculo();
   ConexaoBD conex = new ConexaoBD();
   int flag=1;
 
    
    public CadVeiculos() {
        initComponents();
        CbModelo();
       
        jTextFieldAno.setDocument(new CampoNumerico());       
        jTextFieldRenavan.setDocument(new CampoNumerico());
        jTextFieldAnoModelo.setDocument(new CampoNumerico());
        jTextFieldRenavan.setDocument(new CampoNumerico());
        jTextFieldPlaca.setDocument(new UpperCase());
        jTextFieldCor.setDocument(new UpperCase());
        jTextFieldChassi.setDocument(new UpperCase());
        jTextFieldPlaca.setDocument(new LimiteDigitos() );
        jInternalFrameBuscaVeiculo.setVisible(false);
        
        
        

        jButtonEditar.setEnabled(false);
        jButtonApagar.setEnabled(false);
        jButtonImprimir.setEnabled(false);
        jLabelPlacaObg.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrameBuscaVeiculo = new javax.swing.JInternalFrame();
        jScrollPaneVeiculo = new javax.swing.JScrollPane();
        jTableVeiculo = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonSairIF = new javax.swing.JButton();
        jButtonPesquisarIF = new javax.swing.JButton();
        jLabelFaixaMenu1 = new javax.swing.JLabel();
        JlabelFundoMenuIF = new javax.swing.JLabel();
        jLabelPlaca = new javax.swing.JLabel();
        jTextFieldPlaca = new javax.swing.JTextField();
        jCheckBoxVeiculAtivar = new javax.swing.JCheckBox();
        jLabelMarca = new javax.swing.JLabel();
        jLabelModelo = new javax.swing.JLabel();
        jComboBoxModelo = new javax.swing.JComboBox();
        jTextFieldMarca = new javax.swing.JTextField();
        jButtonBuscarMarca = new javax.swing.JButton();
        jLabelRenavan = new javax.swing.JLabel();
        jTextFieldRenavan = new javax.swing.JTextField();
        jLabelChassi = new javax.swing.JLabel();
        jTextFieldChassi = new javax.swing.JTextField();
        jLabelCor = new javax.swing.JLabel();
        jTextFieldCor = new javax.swing.JTextField();
        jLabelCorAnMo = new javax.swing.JLabel();
        jTextFieldAno = new javax.swing.JTextField();
        jTextFieldAnoModelo = new javax.swing.JTextField();
        jLabelCorAbm = new javax.swing.JLabel();
        jLabelCod = new javax.swing.JLabel();
        jTextFieldCod = new javax.swing.JTextField();
        jLabelPlacaObg = new javax.swing.JLabel();
        jButtonIncluir = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonApagar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jButtonPesquisar = new javax.swing.JButton();
        jButtonImprimir = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelFaixaMenu = new javax.swing.JLabel();
        jLabelFundo = new javax.swing.JLabel();
        jLabelFundo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Veículo");
        setResizable(false);
        getContentPane().setLayout(null);

        jInternalFrameBuscaVeiculo.setTitle("Selecionar Veículo");
        jInternalFrameBuscaVeiculo.setVisible(true);
        jInternalFrameBuscaVeiculo.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableVeiculo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTableVeiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableVeiculo.setGridColor(new java.awt.Color(255, 255, 255));
        jTableVeiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableVeiculoMouseClicked(evt);
            }
        });
        jScrollPaneVeiculo.setViewportView(jTableVeiculo);

        jInternalFrameBuscaVeiculo.getContentPane().add(jScrollPaneVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 330, 160));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel2.setText("False = INATIVO");
        jInternalFrameBuscaVeiculo.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, 10));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel3.setText("True = ATIVO");
        jInternalFrameBuscaVeiculo.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, 10));

        jButtonSairIF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/sair.png"))); // NOI18N
        jButtonSairIF.setToolTipText("Sair");
        jButtonSairIF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairIFActionPerformed(evt);
            }
        });
        jInternalFrameBuscaVeiculo.getContentPane().add(jButtonSairIF, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 45, 30));

        jButtonPesquisarIF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/pesquisar.png"))); // NOI18N
        jButtonPesquisarIF.setToolTipText("Buscar");
        jButtonPesquisarIF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarIFActionPerformed(evt);
            }
        });
        jInternalFrameBuscaVeiculo.getContentPane().add(jButtonPesquisarIF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 45, 30));

        jLabelFaixaMenu1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFaixaMenu1.setForeground(new java.awt.Color(102, 255, 255));
        jLabelFaixaMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menuprincipal_Faixa.png"))); // NOI18N
        jInternalFrameBuscaVeiculo.getContentPane().add(jLabelFaixaMenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 30));

        JlabelFundoMenuIF.setBackground(new java.awt.Color(255, 255, 255));
        JlabelFundoMenuIF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menuprincipal_fundo.png"))); // NOI18N
        JlabelFundoMenuIF.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jInternalFrameBuscaVeiculo.getContentPane().add(JlabelFundoMenuIF, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 10, 560, 180));

        getContentPane().add(jInternalFrameBuscaVeiculo);
        jInternalFrameBuscaVeiculo.setBounds(120, 30, 350, 220);

        jLabelPlaca.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelPlaca.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelPlaca.setText("Placa:");
        getContentPane().add(jLabelPlaca);
        jLabelPlaca.setBounds(20, 70, 50, 25);

        jTextFieldPlaca.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jTextFieldPlaca);
        jTextFieldPlaca.setBounds(80, 70, 140, 25);

        jCheckBoxVeiculAtivar.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxVeiculAtivar.setSelected(true);
        jCheckBoxVeiculAtivar.setText("Ativo?");
        getContentPane().add(jCheckBoxVeiculAtivar);
        jCheckBoxVeiculAtivar.setBounds(490, 40, 55, 23);

        jLabelMarca.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelMarca.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelMarca.setText("Marca:");
        getContentPane().add(jLabelMarca);
        jLabelMarca.setBounds(30, 130, 40, 25);

        jLabelModelo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelModelo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelModelo.setText(" Modelo:");
        getContentPane().add(jLabelModelo);
        jLabelModelo.setBounds(20, 100, 50, 25);

        jComboBoxModelo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBoxModelo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBoxModelo);
        jComboBoxModelo.setBounds(80, 100, 190, 25);

        jTextFieldMarca.setEditable(false);
        jTextFieldMarca.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldMarca.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldMarca.setForeground(new java.awt.Color(51, 0, 255));
        jTextFieldMarca.setToolTipText("");
        getContentPane().add(jTextFieldMarca);
        jTextFieldMarca.setBounds(80, 130, 190, 25);

        jButtonBuscarMarca.setBackground(new java.awt.Color(255, 255, 255));
        jButtonBuscarMarca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/imgBuscar.png"))); // NOI18N
        jButtonBuscarMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarMarcaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscarMarca);
        jButtonBuscarMarca.setBounds(270, 130, 30, 25);

        jLabelRenavan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelRenavan.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelRenavan.setText("Renavam:");
        getContentPane().add(jLabelRenavan);
        jLabelRenavan.setBounds(10, 160, 60, 25);

        jTextFieldRenavan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldRenavan.setToolTipText("");
        getContentPane().add(jTextFieldRenavan);
        jTextFieldRenavan.setBounds(80, 160, 190, 25);

        jLabelChassi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelChassi.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelChassi.setText("Chassi:");
        getContentPane().add(jLabelChassi);
        jLabelChassi.setBounds(320, 160, 60, 25);

        jTextFieldChassi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldChassi.setToolTipText("");
        getContentPane().add(jTextFieldChassi);
        jTextFieldChassi.setBounds(390, 160, 190, 25);

        jLabelCor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelCor.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelCor.setText("Cor:");
        getContentPane().add(jLabelCor);
        jLabelCor.setBounds(320, 130, 60, 25);

        jTextFieldCor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldCor.setToolTipText("");
        getContentPane().add(jTextFieldCor);
        jTextFieldCor.setBounds(390, 130, 190, 25);

        jLabelCorAnMo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelCorAnMo.setText(" /");
        getContentPane().add(jLabelCorAnMo);
        jLabelCorAnMo.setBounds(450, 100, 10, 25);

        jTextFieldAno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldAno.setToolTipText("");
        getContentPane().add(jTextFieldAno);
        jTextFieldAno.setBounds(390, 100, 60, 25);

        jTextFieldAnoModelo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldAnoModelo.setToolTipText("");
        getContentPane().add(jTextFieldAnoModelo);
        jTextFieldAnoModelo.setBounds(460, 100, 60, 25);

        jLabelCorAbm.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelCorAbm.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelCorAbm.setText("Ano / Modelo:");
        getContentPane().add(jLabelCorAbm);
        jLabelCorAbm.setBounds(300, 100, 80, 25);

        jLabelCod.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelCod.setText("Código:");
        getContentPane().add(jLabelCod);
        jLabelCod.setBounds(10, 40, 60, 25);

        jTextFieldCod.setEditable(false);
        jTextFieldCod.setEnabled(false);
        jTextFieldCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCod);
        jTextFieldCod.setBounds(80, 40, 60, 25);

        jLabelPlacaObg.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabelPlacaObg.setForeground(new java.awt.Color(255, 0, 0));
        jLabelPlacaObg.setText("Obrigatório");
        getContentPane().add(jLabelPlacaObg);
        jLabelPlacaObg.setBounds(220, 70, 60, 30);

        jButtonIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/incluir.png"))); // NOI18N
        jButtonIncluir.setToolTipText("Incluir");
        jButtonIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonIncluir);
        jButtonIncluir.setBounds(10, 0, 45, 30);

        jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/salvar.png"))); // NOI18N
        jButtonEditar.setToolTipText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEditar);
        jButtonEditar.setBounds(60, 0, 45, 30);

        jButtonApagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/apagar.png"))); // NOI18N
        jButtonApagar.setToolTipText("Deletar");
        jButtonApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApagarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonApagar);
        jButtonApagar.setBounds(110, 0, 45, 30);

        jButtonLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/limpar.png"))); // NOI18N
        jButtonLimpar.setToolTipText("Limpar");
        jButtonLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonLimparMouseClicked(evt);
            }
        });
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLimpar);
        jButtonLimpar.setBounds(160, 0, 45, 30);

        jButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/pesquisar.png"))); // NOI18N
        jButtonPesquisar.setToolTipText("Buscar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPesquisar);
        jButtonPesquisar.setBounds(210, 0, 45, 30);

        jButtonImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/imprimir.png"))); // NOI18N
        jButtonImprimir.setToolTipText("Imprimir");
        getContentPane().add(jButtonImprimir);
        jButtonImprimir.setBounds(260, 0, 45, 30);

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/sair.png"))); // NOI18N
        jButtonSair.setToolTipText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSair);
        jButtonSair.setBounds(310, 0, 45, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("* Campos de preenchimento obrigatório.");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 200, 220, 14);

        jLabelFaixaMenu.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFaixaMenu.setForeground(new java.awt.Color(102, 255, 255));
        jLabelFaixaMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menuprincipal_Faixa.png"))); // NOI18N
        getContentPane().add(jLabelFaixaMenu);
        jLabelFaixaMenu.setBounds(0, 0, 650, 30);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menuprincipal_fundo.png"))); // NOI18N
        getContentPane().add(jLabelFundo);
        jLabelFundo.setBounds(0, 30, 640, 280);

        jLabelFundo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menuprincipal_fundo.png"))); // NOI18N
        getContentPane().add(jLabelFundo1);
        jLabelFundo1.setBounds(0, 30, 640, 260);

        setSize(new java.awt.Dimension(621, 262));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void CbModelo(){
    
        conex.conexao();
        conex.executaSql("select *from tbl_modelo order by descricao");
        try{
            conex.rs.first();
            jComboBoxModelo.removeAllItems();
            do{
               jComboBoxModelo.addItem(conex.rs.getString("descricao"));
            }while(conex.rs.next());
            
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(rootPane, "Erro ao preecher dados");
        }
        conex.desconecta();      
    }
    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        CadACadastros cad = new CadACadastros();
        cad.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLimparMouseClicked
    jButtonIncluir.setEnabled(true);
    jButtonApagar.setEnabled(false);
    jButtonEditar.setEnabled(false);
    jTextFieldAno.setText(null); 
    jTextFieldAnoModelo.setText(null);
    jTextFieldChassi.setText(null);
    jTextFieldCor.setText(null);
    jComboBoxModelo.setSelectedIndex(0); //VER SE FUNCIONAL
    jTextFieldMarca.setText(null);
    jTextFieldPlaca.setText(null);
    jTextFieldRenavan.setText(null);
    jTextFieldCod.setText(null);
    jLabelPlacaObg.setVisible(false);
    jCheckBoxVeiculAtivar.setSelected(false);
    }//GEN-LAST:event_jButtonLimparMouseClicked

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirActionPerformed
        if(jTextFieldPlaca.getText().isEmpty() || Integer.valueOf(jTextFieldAnoModelo.getText()) < Integer.valueOf(jTextFieldAno.getText())){
         if(jTextFieldPlaca.getText().isEmpty()) { 
          jLabelPlacaObg.setVisible(true);
          JOptionPane.showMessageDialog(null, "Campo Obrigatório");
          jTextFieldPlaca.requestFocus();  
        }
        if(Integer.valueOf(jTextFieldAnoModelo.getText()) < Integer.valueOf(jTextFieldAno.getText()) ) {            
        JOptionPane.showMessageDialog(null, "O ano de modelo deve ser maior ou igual ao ano de fabricação");
        }
       
        }
       
        else{
        mod.setPlaca(jTextFieldPlaca.getText());
        mod.setRenavan(Integer.parseInt(jTextFieldRenavan.getText()));
        mod.setChassi(jTextFieldChassi.getText());
        mod.setCor(jTextFieldCor.getText());
        mod.setAtivar(jCheckBoxVeiculAtivar.isSelected()); 
        mod.setAno(Integer.parseInt(jTextFieldAno.getText()));
        mod.setAnoModelo(Integer.parseInt(jTextFieldAno.getText()));
        mod.setModelo((String) jComboBoxModelo.getSelectedItem());
        control.Salvar(mod);
       
        mod.setPlaca(jTextFieldPlaca.getText());
        BeansVeiculo model = control.Pesquisar(mod);
        jTextFieldCod.setText(String.valueOf(model.getCodigo()));
        
        jButtonIncluir.setEnabled(false);
        jButtonEditar.setEnabled(true);
        jButtonApagar.setEnabled(true);
        jLabelPlacaObg.setVisible(false);
        }
      
        
        /*
        if(jTextFieldPlaca.getText().isEmpty()) { 
          jLabelPlacaObg.setVisible(true);
          JOptionPane.showMessageDialog(null, "Campo Obrigatório");
          jTextFieldPlaca.requestFocus();  
        }
        else{
        mod.setPlaca(jTextFieldPlaca.getText());
        
        if(jTextFieldRenavan.getText().length() > 0){
        mod.setRenavan(Integer.parseInt(jTextFieldRenavan.getText()));
        }
        //mod.setRenavan(Integer.parseInt(jTextFieldRenavan.getText()));
        mod.setChassi(jTextFieldChassi.getText());
        mod.setCor(jTextFieldCor.getText());
        mod.setAtivar(jCheckBoxVeiculAtivar.isSelected()); 
        mod.setAno(Integer.parseInt(jTextFieldAno.getText()));
        mod.setAnoModelo(Integer.parseInt(jTextFieldAnoModelo.getText()));
        mod.setModelo((String) jComboBoxModelo.getSelectedItem());
        jButtonIncluir.setEnabled(false);
        jButtonEditar.setEnabled(true);
        jButtonApagar.setEnabled(true);
       jLabelPlacaObg.setVisible(false);
        }
        int a = mod.getAno();
        int b = mod.getAnoModelo();
        
        if( a <= b ){
        control.Salvar(mod);
        mod.setPlaca(jTextFieldPlaca.getText());   
        BeansVeiculo model = control.Pesquisar(mod);
        jTextFieldCod.setText(String.valueOf(model.getCodigo()));
        

        } else{
            JOptionPane.showMessageDialog(null, "O ano de modelo deve ser maior ou igual ao ano de fabricação");
            jTextFieldAnoModelo.requestFocus();
        }  */ 
    }//GEN-LAST:event_jButtonIncluirActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed

        PreencherTabelaIF("select a.id_veiculo, a.placa, b.descricao,a.ativo from tbl_veiculo as a inner join tbl_modelo as b on(a.id_modelo = b.id_modelo)");
        jInternalFrameBuscaVeiculo.setVisible(true);
        
        
        /*
        if (jTextFieldPlaca.getText().length() > 0) { 
            mod.setPesquisar(jTextFieldPlaca.getText());
            BeansVeiculo model = control.Pesquisar(mod);
            jTextFieldCod.setText(String.valueOf(model.getCodigo()));
            jTextFieldPlaca.setText(model.getPlaca().toUpperCase()) ;
            jTextFieldAno.setText(String.valueOf(model.getAno()));
            jTextFieldAnoModelo.setText(String.valueOf(model.getAnoModelo()));
            jTextFieldRenavan.setText(String.valueOf(model.getRenavan()));
            jTextFieldCor.setText(model.getCor());
            jTextFieldChassi.setText(model.getChassi());
            jCheckBoxVeiculAtivar.setSelected(model.isAtivar());
            jComboBoxModelo.setSelectedItem(model.getModelo());
            
            control.PesquisarMarca(mod);
            jTextFieldMarca.setText(model.getMarca());
            
            jButtonIncluir.setEnabled(false);
            jButtonEditar.setEnabled(true);
            jButtonApagar.setEnabled(true);
            jLabelPlacaObg.setVisible(false);
            }else{
            jLabelPlacaObg.setVisible(true);
            JOptionPane.showMessageDialog(null, "Campo Obrigatório");
            jTextFieldPlaca.requestFocus();
        
        }
            */
            
            
           
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jTextFieldCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodActionPerformed
        
    }//GEN-LAST:event_jTextFieldCodActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
    if(jTextFieldPlaca.getText().isEmpty() || Integer.valueOf(jTextFieldAnoModelo.getText()) < Integer.valueOf(jTextFieldAno.getText())){
         if(jTextFieldPlaca.getText().isEmpty()) { 
          jLabelPlacaObg.setVisible(true);
          JOptionPane.showMessageDialog(null, "Campo Obrigatório");
          jTextFieldPlaca.requestFocus();  
        }
        if(Integer.valueOf(jTextFieldAnoModelo.getText()) < Integer.valueOf(jTextFieldAno.getText()) ) {            
        JOptionPane.showMessageDialog(null, "O ano de modelo deve ser maior ou igual ao ano de fabricação");
        }
        }
       
        else{
        mod.setPlaca(jTextFieldPlaca.getText());
        mod.setRenavan(Integer.parseInt(jTextFieldRenavan.getText()));
        mod.setChassi(jTextFieldChassi.getText());
        mod.setCor(jTextFieldCor.getText());
        mod.setAtivar(jCheckBoxVeiculAtivar.isSelected()); 
        mod.setAno(Integer.parseInt(jTextFieldAno.getText()));
        mod.setAnoModelo(Integer.parseInt(jTextFieldAno.getText()));
        mod.setModelo((String) jComboBoxModelo.getSelectedItem());
        control.Editar(mod);
       
        mod.setPlaca(jTextFieldPlaca.getText());
        BeansVeiculo model = control.Pesquisar(mod);
        jTextFieldCod.setText(String.valueOf(model.getCodigo()));
        
        jButtonIncluir.setEnabled(false);
        jButtonEditar.setEnabled(true);
        jButtonApagar.setEnabled(true);
        jLabelPlacaObg.setVisible(false);
        }
        
        
        
        /*       if (jTextFieldPlaca.getText().length() > 0) {
            mod.setPlaca(jTextFieldPlaca.getText());
            mod.setRenavan(Integer.parseInt(jTextFieldRenavan.getText()));
            mod.setChassi(jTextFieldChassi.getText());
            mod.setCor(jTextFieldCor.getText());
            mod.setAtivar(jCheckBoxVeiculAtivar.isSelected()); 
            mod.setAno(Integer.parseInt(jTextFieldAno.getText()));
            mod.setAnoModelo(Integer.parseInt(jTextFieldAnoModelo.getText()));
            mod.setModelo((String) jComboBoxModelo.getSelectedItem());
            control.Editar(mod);
            
            jLabelPlacaObg.setVisible(false);
            jButtonIncluir.setEnabled(false);
            }else {
                jLabelPlacaObg.setVisible(true);
                JOptionPane.showMessageDialog(null, "Campo Obrigatório");
                jTextFieldPlaca.requestFocus();
            } 
        */
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApagarActionPerformed
        
         if(flag==1){
            int Confirm = JOptionPane.showConfirmDialog(null,"Excluir registro?"," Excluir", JOptionPane.YES_NO_OPTION);
                if (Confirm == JOptionPane.YES_OPTION) {
                mod.setCodigo(Integer.parseInt(jTextFieldCod.getText()));
                mod.setPlaca(jTextFieldPlaca.getText());
                control.Excluir(mod); 

                jTextFieldAno.setText(""); 
                jTextFieldAnoModelo.setText("");
                jTextFieldChassi.setText("");
                jTextFieldCor.setText("");
                //jComboBoxModelo.setSelectedIndex(0);
                jTextFieldMarca.setText("");
                jTextFieldPlaca.setText("");
                jTextFieldRenavan.setText("");
                jTextFieldCod.setText("");
                
                jButtonApagar.setEnabled(false);
                jButtonEditar.setEnabled(false);
                jButtonIncluir.setEnabled(true);
                
                }else if (Confirm == JOptionPane.NO_OPTION){
                setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                }
        }else{
            int Confirm = JOptionPane.showConfirmDialog(null,"Excluir registro?"," Excluir", JOptionPane.YES_NO_OPTION);
                if (Confirm == JOptionPane.YES_OPTION) {
                mod.setCodigo(Integer.parseInt(jTextFieldCod.getText()));
                mod.setPlaca(jTextFieldPlaca.getText());
                control.Excluir(mod);   
                jLabelPlacaObg.setVisible(false);
                jButtonEditar.setEnabled(false);
                jButtonApagar.setEnabled(false);
                }else if (Confirm == JOptionPane.NO_OPTION){
                setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                }
        }
    }//GEN-LAST:event_jButtonApagarActionPerformed

    private void jButtonBuscarMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarMarcaActionPerformed
        mod.setModelo((String) jComboBoxModelo.getSelectedItem());
        BeansVeiculo model = control.PesquisarMarca(mod);
        jTextFieldMarca.setText(model.getMarca());
    }//GEN-LAST:event_jButtonBuscarMarcaActionPerformed

    private void jTableVeiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableVeiculoMouseClicked
        String placa = ""+jTableVeiculo.getValueAt(jTableVeiculo.getSelectedRow(), 1);

            mod.setPlaca(placa);
            BeansVeiculo model = control.Pesquisar(mod);
            jTextFieldCod.setText(String.valueOf(model.getCodigo()));
            jTextFieldPlaca.setText(model.getPlaca().toUpperCase()) ;
            jTextFieldAno.setText(String.valueOf(model.getAno()));
            jTextFieldAnoModelo.setText(String.valueOf(model.getAnoModelo()));
            jTextFieldRenavan.setText(String.valueOf(model.getRenavan()));
            jTextFieldCor.setText(model.getCor());
            jTextFieldChassi.setText(model.getChassi());
            jCheckBoxVeiculAtivar.setSelected(model.isAtivar());
            jComboBoxModelo.setSelectedItem(model.getModelo());
            
            control.PesquisarMarca(mod);
            jTextFieldMarca.setText(model.getMarca());
            
            jInternalFrameBuscaVeiculo.setVisible(false);
            jButtonIncluir.setEnabled(false);
            jButtonEditar.setEnabled(true);
            jButtonApagar.setEnabled(true);
            

        
    }//GEN-LAST:event_jTableVeiculoMouseClicked

    private void jButtonSairIFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairIFActionPerformed
        jInternalFrameBuscaVeiculo.dispose();
    }//GEN-LAST:event_jButtonSairIFActionPerformed

    private void jButtonPesquisarIFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarIFActionPerformed
        PreencherTabelaIF("select a.id_veiculo, a.placa, b.descricao,a.ativo from tbl_veiculo as a inner join tbl_modelo as b on(a.id_modelo = b.id_modelo)");
    }//GEN-LAST:event_jButtonPesquisarIFActionPerformed
 
   
    public void PreencherTabelaIF(String SQL){
      ArrayList dados = new ArrayList();
      String[] colunas = new String[]{"COD","PLACA","MODELO","STATUS"};
      
      conex.conexao();
      conex.executaSql(SQL);

      try{
          conex.rs.first();       
          do{
              dados.add(new Object[]{conex.rs.getInt("id_veiculo"),
                                     conex.rs.getString("placa"),
                                     conex.rs.getString("descricao"),
                                     conex.rs.getBoolean("ativo")
                                   
                                    });
 
          }while(conex.rs.next());
      
        }catch(SQLException ex){
          JOptionPane.showMessageDialog(null, "Erro ao preencher ArrayList\nErro:"+ex);
        }
          
     BeansTabelas modelo = new BeansTabelas(dados, colunas);
      
     jTableVeiculo.setModel(modelo);
     jTableVeiculo.getColumnModel().getColumn(0).setPreferredWidth(40);
     jTableVeiculo.getColumnModel().getColumn(0).setResizable(false);
     jTableVeiculo.getColumnModel().getColumn(0).setHeaderValue("COD");
     jTableVeiculo.getColumnModel().getColumn(1).setPreferredWidth(80);
     jTableVeiculo.getColumnModel().getColumn(1).setResizable(false); //não redimensionaveL
     jTableVeiculo.getColumnModel().getColumn(1).setHeaderValue("PLACA");
     jTableVeiculo.getColumnModel().getColumn(2).setPreferredWidth(110);
     jTableVeiculo.getColumnModel().getColumn(2).setResizable(false); //não redimensionaveL
     jTableVeiculo.getColumnModel().getColumn(2).setHeaderValue("MODELO");
     jTableVeiculo.getColumnModel().getColumn(3).setPreferredWidth(70);
     jTableVeiculo.getColumnModel().getColumn(3).setResizable(false); //não redimensionaveL
     jTableVeiculo.getColumnModel().getColumn(3).setHeaderValue("STATUS");
           

     jTableVeiculo.getTableHeader().setReorderingAllowed(false); //não reordenavel
     jTableVeiculo.setAutoResizeMode(jTableVeiculo.AUTO_RESIZE_OFF); //não redmencionar
     jTableVeiculo.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);//selicioar um dado por vez
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPadrao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPadrao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPadrao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPadrao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPadrao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JlabelFundoMenuIF;
    private javax.swing.JButton jButtonApagar;
    private javax.swing.JButton jButtonBuscarMarca;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonImprimir;
    private javax.swing.JButton jButtonIncluir;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonPesquisarIF;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSairIF;
    private javax.swing.JCheckBox jCheckBoxVeiculAtivar;
    private javax.swing.JComboBox jComboBoxModelo;
    private javax.swing.JInternalFrame jInternalFrameBuscaVeiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelChassi;
    private javax.swing.JLabel jLabelCod;
    private javax.swing.JLabel jLabelCor;
    private javax.swing.JLabel jLabelCorAbm;
    private javax.swing.JLabel jLabelCorAnMo;
    private javax.swing.JLabel jLabelFaixaMenu;
    private javax.swing.JLabel jLabelFaixaMenu1;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelFundo1;
    private javax.swing.JLabel jLabelMarca;
    private javax.swing.JLabel jLabelModelo;
    private javax.swing.JLabel jLabelPlaca;
    private javax.swing.JLabel jLabelPlacaObg;
    private javax.swing.JLabel jLabelRenavan;
    private javax.swing.JScrollPane jScrollPaneVeiculo;
    private javax.swing.JTable jTableVeiculo;
    private javax.swing.JTextField jTextFieldAno;
    private javax.swing.JTextField jTextFieldAnoModelo;
    private javax.swing.JTextField jTextFieldChassi;
    private javax.swing.JTextField jTextFieldCod;
    private javax.swing.JTextField jTextFieldCor;
    private javax.swing.JTextField jTextFieldMarca;
    private javax.swing.JTextField jTextFieldPlaca;
    private javax.swing.JTextField jTextFieldRenavan;
    // End of variables declaration//GEN-END:variables
}
