/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visaoMaster;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import Beans.BeansMarca;
import Beans.BeansTabelas;
import modeloConection.ConexaoBD;
import modeloDao.DaoMarca;
import controller.UpperCase;


/**
 *
 * @author Professor
 */
public class TbMarca extends javax.swing.JFrame {

    BeansMarca mod = new BeansMarca();
    DaoMarca control = new DaoMarca();
    ConexaoBD conex = new ConexaoBD();
    int flag;
 
    public TbMarca() {
        initComponents();
        jButtonEditar.setEnabled(false);
        jButtonApagar.setEnabled(false);
        jButtonImprimir.setEnabled(false);
       jLabelDescObgt.setVisible(false);
       jTextFieldDescricao.setDocument(new UpperCase());
       jInternalFrameBuscaMarca.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrameBuscaMarca = new javax.swing.JInternalFrame();
        jScrollPaneMarca = new javax.swing.JScrollPane();
        jTableMarca = new javax.swing.JTable();
        jButtonSairIF = new javax.swing.JButton();
        jButtonPesquisarIF = new javax.swing.JButton();
        jLabelFaixaMenu1 = new javax.swing.JLabel();
        JlabelFundoMenuIF = new javax.swing.JLabel();
        jTextFieldDescricao = new javax.swing.JTextField();
        jLabelDescricao = new javax.swing.JLabel();
        jLabelCod = new javax.swing.JLabel();
        jTextFieldCod = new javax.swing.JTextField();
        jLabelDescObgt = new javax.swing.JLabel();
        jButtonIncluir = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonApagar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jButtonPesquisar = new javax.swing.JButton();
        jButtonImprimir = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelFaixaMenu = new javax.swing.JLabel();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Marca");
        setResizable(false);
        getContentPane().setLayout(null);

        jInternalFrameBuscaMarca.setTitle("Selecionar Marca");
        jInternalFrameBuscaMarca.setVisible(true);
        jInternalFrameBuscaMarca.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableMarca.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jTableMarca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableMarca.setGridColor(new java.awt.Color(255, 255, 255));
        jTableMarca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMarcaMouseClicked(evt);
            }
        });
        jScrollPaneMarca.setViewportView(jTableMarca);

        jInternalFrameBuscaMarca.getContentPane().add(jScrollPaneMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 410, 130));

        jButtonSairIF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/sair.png"))); // NOI18N
        jButtonSairIF.setToolTipText("Sair");
        jButtonSairIF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairIFActionPerformed(evt);
            }
        });
        jInternalFrameBuscaMarca.getContentPane().add(jButtonSairIF, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 45, 30));

        jButtonPesquisarIF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/pesquisar.png"))); // NOI18N
        jButtonPesquisarIF.setToolTipText("Buscar");
        jButtonPesquisarIF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarIFActionPerformed(evt);
            }
        });
        jInternalFrameBuscaMarca.getContentPane().add(jButtonPesquisarIF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 45, 30));

        jLabelFaixaMenu1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFaixaMenu1.setForeground(new java.awt.Color(102, 255, 255));
        jLabelFaixaMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menuprincipal_Faixa.png"))); // NOI18N
        jInternalFrameBuscaMarca.getContentPane().add(jLabelFaixaMenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 30));

        JlabelFundoMenuIF.setBackground(new java.awt.Color(255, 255, 255));
        JlabelFundoMenuIF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menuprincipal_fundo.png"))); // NOI18N
        JlabelFundoMenuIF.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jInternalFrameBuscaMarca.getContentPane().add(JlabelFundoMenuIF, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 10, 420, 180));

        getContentPane().add(jInternalFrameBuscaMarca);
        jInternalFrameBuscaMarca.setBounds(30, 0, 430, 190);

        jTextFieldDescricao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDescricaoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldDescricao);
        jTextFieldDescricao.setBounds(100, 90, 260, 25);

        jLabelDescricao.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelDescricao.setText("Descrição:");
        getContentPane().add(jLabelDescricao);
        jLabelDescricao.setBounds(30, 90, 60, 25);

        jLabelCod.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelCod.setText("Código:");
        getContentPane().add(jLabelCod);
        jLabelCod.setBounds(30, 50, 60, 25);

        jTextFieldCod.setEditable(false);
        jTextFieldCod.setEnabled(false);
        jTextFieldCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCod);
        jTextFieldCod.setBounds(100, 50, 60, 25);

        jLabelDescObgt.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabelDescObgt.setForeground(new java.awt.Color(255, 0, 0));
        jLabelDescObgt.setText("Obrigatório");
        getContentPane().add(jLabelDescObgt);
        jLabelDescObgt.setBounds(360, 90, 70, 20);

        jButtonIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/incluir.png"))); // NOI18N
        jButtonIncluir.setToolTipText("Incluir");
        jButtonIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonIncluir);
        jButtonIncluir.setBounds(10, 0, 45, 30);

        jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/salvar.png"))); // NOI18N
        jButtonEditar.setToolTipText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEditar);
        jButtonEditar.setBounds(60, 0, 45, 30);

        jButtonApagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/apagar.png"))); // NOI18N
        jButtonApagar.setToolTipText("Deletar");
        jButtonApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApagarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonApagar);
        jButtonApagar.setBounds(110, 0, 45, 30);

        jButtonLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/limpar.png"))); // NOI18N
        jButtonLimpar.setToolTipText("Limpar");
        jButtonLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonLimparMouseClicked(evt);
            }
        });
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLimpar);
        jButtonLimpar.setBounds(160, 0, 45, 30);

        jButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/pesquisar.png"))); // NOI18N
        jButtonPesquisar.setToolTipText("Buscar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPesquisar);
        jButtonPesquisar.setBounds(210, 0, 45, 30);

        jButtonImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/imprimir.png"))); // NOI18N
        jButtonImprimir.setToolTipText("Imprimir");
        getContentPane().add(jButtonImprimir);
        jButtonImprimir.setBounds(260, 0, 45, 30);

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/sair.png"))); // NOI18N
        jButtonSair.setToolTipText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSair);
        jButtonSair.setBounds(310, 0, 45, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("* Campos de preenchimento obrigatório.");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 180, 220, 14);

        jLabelFaixaMenu.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFaixaMenu.setForeground(new java.awt.Color(102, 255, 255));
        jLabelFaixaMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menuprincipal_Faixa.png"))); // NOI18N
        getContentPane().add(jLabelFaixaMenu);
        jLabelFaixaMenu.setBounds(0, 0, 500, 30);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menuprincipal_fundo.png"))); // NOI18N
        getContentPane().add(jLabelFundo);
        jLabelFundo.setBounds(0, 30, 500, 180);

        setSize(new java.awt.Dimension(505, 236));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        TbATabelasAuxiliares selecTab = new TbATabelasAuxiliares();
        selecTab.setVisible(true);
        dispose();  
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLimparMouseClicked
        jTextFieldDescricao.setText("");
        jTextFieldCod.setText("");
        jButtonIncluir.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonApagar.setEnabled(false);
        jLabelDescObgt.setVisible(false);
    }//GEN-LAST:event_jButtonLimparMouseClicked

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jTextFieldDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDescricaoActionPerformed
        
    }//GEN-LAST:event_jTextFieldDescricaoActionPerformed

    private void jButtonIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirActionPerformed
       
        if(jTextFieldDescricao.getText().isEmpty()) {
          jLabelDescObgt.setVisible(true);
          JOptionPane.showMessageDialog(null, "Campo Obrigatório");
          jTextFieldDescricao.requestFocus();
        }else {
          mod.setDescricao(jTextFieldDescricao.getText());
          control.Salvar(mod);
          //jTextFieldCod.setText(String.valueOf(mod.getCodigo()));
          jLabelDescObgt.setVisible(false);
          jButtonIncluir.setEnabled(false);
          jButtonEditar.setEnabled(true);
          jButtonApagar.setEnabled(true);
          
            mod.setPesquisar(jTextFieldDescricao.getText());
            BeansMarca model = control.Pesquisar(mod);
            jTextFieldCod.setText(String.valueOf(model.getCodigo()));
            //jTextFieldDescricao.setText(model.getDescricao()) ;
        }       
    }//GEN-LAST:event_jButtonIncluirActionPerformed

    private void jTextFieldCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodActionPerformed
        
    }//GEN-LAST:event_jTextFieldCodActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        PreencherTabelaIF("select id_marca, descricaomarca from tbl_marca order by descricaomarca");
        jInternalFrameBuscaMarca.setVisible(true);
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApagarActionPerformed
        if(flag==1){
        mod.setDescricao(jTextFieldDescricao.getText()); 
        JOptionPane.showMessageDialog(null, "Excluir Registro?");
        control.Excluir(mod);
        jTextFieldDescricao.setText("");
        jTextFieldCod.setText("");
        
        }else{
            int Confirm = JOptionPane.showConfirmDialog(null,"Excluir registro?"," Excluir", JOptionPane.YES_NO_OPTION);
            if (Confirm == JOptionPane.YES_OPTION) {
            mod.setCodigo(Integer.parseInt(jTextFieldCod.getText()));
            mod.setDescricao(jTextFieldDescricao.getText());
            control.Excluir(mod);
            
            jTextFieldDescricao.setText("");
            jTextFieldCod.setText("");
            jButtonEditar.setEnabled(false);
            jButtonApagar.setEnabled(false);
            jLabelDescObgt.setVisible(false);
            jButtonIncluir.setEnabled(true);
            }else if (Confirm == JOptionPane.NO_OPTION){
                setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            }
        }
    }//GEN-LAST:event_jButtonApagarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed

            if (jTextFieldDescricao.getText().length() > 0) { 
                mod.setCodigo(Integer.parseInt(jTextFieldCod.getText()));
                mod.setDescricao(jTextFieldDescricao.getText());
                control.Editar(mod);
                jLabelDescObgt.setVisible(false);
            }
            else {
                jLabelDescObgt.setVisible(true);
                JOptionPane.showMessageDialog(null, "Campo Obrigatório");
                jTextFieldDescricao.requestFocus();    
            }   
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jTableMarcaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMarcaMouseClicked
        String descricaomarca = ""+jTableMarca.getValueAt(jTableMarca.getSelectedRow(), 1);

        conex.executaSql("select id_marca, descricaomarca from tbl_marca where descricaomarca ilike '%"+descricaomarca+"%'");
        try {
            conex.rs.first();
            mod.setCodigo(conex.rs.getInt("id_marca"));
            mod.setDescricao(conex.rs.getString("descricaomarca"));

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Veículo não encontrado"+ex);
        }

        jTextFieldCod.setText(String.valueOf(mod.getCodigo()));
        jTextFieldDescricao.setText(mod.getDescricao());

        conex.desconecta();
        jInternalFrameBuscaMarca.dispose();
        jButtonApagar.setEnabled(true);
        jButtonEditar.setEnabled(true);
        jButtonIncluir.setEnabled(false);
    }//GEN-LAST:event_jTableMarcaMouseClicked

    private void jButtonSairIFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairIFActionPerformed
        jInternalFrameBuscaMarca.dispose();
    }//GEN-LAST:event_jButtonSairIFActionPerformed

    private void jButtonPesquisarIFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarIFActionPerformed
        PreencherTabelaIF("select id_marca, descricaomarca from tbl_marca order by descricaomarca");
        
    }//GEN-LAST:event_jButtonPesquisarIFActionPerformed

    public void PreencherTabelaIF(String SQL){
      ArrayList dados = new ArrayList();
      String[] colunas = new String[]{"COD","MARCA"};
      
      conex.conexao();
      conex.executaSql(SQL);

      try{
          conex.rs.first();       
          do{
              dados.add(new Object[]{conex.rs.getInt("id_marca"),
                                     conex.rs.getString("descricaomarca")
                                   
                                    });
 
          }while(conex.rs.next());
      
        }catch(SQLException ex){
          JOptionPane.showMessageDialog(null, "Erro ao preencher ArrayList\nErro:"+ex);
        }
          
     BeansTabelas modelo = new BeansTabelas(dados, colunas);
      
     jTableMarca.setModel(modelo);
     jTableMarca.getColumnModel().getColumn(0).setPreferredWidth(45);
     jTableMarca.getColumnModel().getColumn(0).setResizable(true);
     jTableMarca.getColumnModel().getColumn(0).setHeaderValue("COD");
     jTableMarca.getColumnModel().getColumn(1).setPreferredWidth(342);
     jTableMarca.getColumnModel().getColumn(1).setResizable(true); //não redimensionaveL
     jTableMarca.getColumnModel().getColumn(1).setHeaderValue("MARCA");
           

     jTableMarca.getTableHeader().setReorderingAllowed(false); //não reordenavel
     jTableMarca.setAutoResizeMode(jTableMarca.AUTO_RESIZE_OFF); //não redmencionar
     jTableMarca.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);//selicioar um dado por vez
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPadrao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPadrao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPadrao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPadrao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPadrao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JlabelFundoMenuIF;
    private javax.swing.JButton jButtonApagar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonImprimir;
    private javax.swing.JButton jButtonIncluir;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonPesquisarIF;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSairIF;
    private javax.swing.JInternalFrame jInternalFrameBuscaMarca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCod;
    private javax.swing.JLabel jLabelDescObgt;
    private javax.swing.JLabel jLabelDescricao;
    private javax.swing.JLabel jLabelFaixaMenu;
    private javax.swing.JLabel jLabelFaixaMenu1;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JScrollPane jScrollPaneMarca;
    private javax.swing.JTable jTableMarca;
    private javax.swing.JTextField jTextFieldCod;
    private javax.swing.JTextField jTextFieldDescricao;
    // End of variables declaration//GEN-END:variables
}
